### ISSUE TITLE
No icon shown on flathub.org

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.libreoffice.LibreOffice#1]
The icon is missing here [0] and here [1]. However, the launcher has an icon after installing LibreOffice from Flathub.

[0] https://flathub.org/apps.html
[1] http://45.55.104.129/apps

**Comment by stbergmann** [comment]
Yes, this has just been discussed on #flathub.  (There's a broken link between org.libreoffice.LibreOffice.appdata.xml's <id>org.libreoffice.LibreOffice.desktop</id> and the single org.libreoffice.LibreOffice.desktop having been replaced with the LO upstream bunch of org.libreoffice.LibreOffice-*.desktop files.)  I'm working on a fix and will include that in a fresh LO 5.4.3 build (which has meanwhile been released upstream, anyway).

**Comment by stbergmann** [comment]
Fixed with <https://github.com/flathub/org.libreoffice.LibreOffice/commit/4f9a0d374d990b7e0f2e162ba0a181270078e523> "Backport master patch needed for AppData icon".  (<http://45.55.104.129/apps> already shows that icon, while <https://flathub.org/apps.html> appears to be lagging behind.)
