### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.libreoffice.LibreOffice#101]

**Comment by Erick555** [comment]
This needs [org.freedesktop.Sdk.Extension.openjdk11](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11) version for 19.08 as precondition.

**Comment by x80486** [comment]
...and that's already updated :wink:

**Comment by Erick555** [comment]
I'm working on update here but it's little tricky: https://github.com/flathub/org.libreoffice.LibreOffice/pull/102

**Comment by stbergmann** [comment]
Done with <https://github.com/flathub/org.libreoffice.LibreOffice/commit/ce11e79afc4fade5b235a33c0dd5fcc90aa4474f> "Merge pull request #104 from flathub/freedesktop19.08".

Note that this means that there will be no more i386 builds of LibreOffice (as org.freedesktop.Sdk//19.08 dropped support for that arch as I was told on #flatpak IRC).
