### ISSUE TITLE
libre writer Flatpak crsahing

### ISSUE THREAD

**Issue by inputbim** [flathub/org.libreoffice.LibreOffice#109]
running elementary os Hera, installed libre from flathub, was working whole day, then suddenly I keep getting crashing, terminal is saying:

![image](https://user-images.githubusercontent.com/59498682/72208381-9e1ce580-34aa-11ea-8861-32470fc2d34a.png)

**Comment by stbergmann** [comment]
Not sure what you consider an error here.  If you run LibreOffice with arguments `@@u`, `%U`, and `@@` (which it interprets as---relative---pathnames), it will (likely) respond that those files do not exist.
(And the `Failed to load module` messages are harmless.)
