### ISSUE TITLE
Update to LibreOffice 6.0.0

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.libreoffice.LibreOffice#11]

**Comment by stbergmann** [comment]
I'm actually working on that, see <https://github.com/flathub/org.libreoffice.LibreOffice/pull/10>.  However, for one, the flathub builders are a bit overworked at the moment, it appears, and for another, I ponder waiting for <https://github.com/flathub/org.libreoffice.LibreOffice/pull/9> being in good shape and include that, so we'd also get an arm build.

**Comment by stbergmann** [comment]
<https://flathub.org/builds/#/builders/1/builds/1918> (but without an arm build after all, for now)
