### ISSUE TITLE
GTK bookmarks do not appear in the flatpak version of LibreOffice

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [flathub/org.libreoffice.LibreOffice#111]
In the latest manually downloadable version of LibreOffice (LO), GTK bookmarks show up in LO's file picker (when that picker is set to use the computer's native format). They do _not_ show up in the flatpak. This is considerably inconvenient. Nor is moving to the download version really an option, for using that (or indeed the PPA) to keep LO up to date works poorly (in the case of the .deb version, because installation is a hassle because one must download an archive and then install all the .deb files it contains).

Flatpak: org.libreoffice.LibreOffice/x86_64/stable system,current
OS, distro & DE: Linux Mint 19.2 Cinnamon x64.

It may be relevant that when running any non-flatpak version of LO I see an error about Default.ott not existing.

Cf. perhaps #96.

**Comment by nekohayo** [comment]
My understanding is that it uses its own "copy" of the GTK settings / user config within the sandboxed environment. To my surprise today, as I installed LibreOffice from Flatpak for the first time in roughly 7 years, I saw bookmarks in there to folders from a company I last worked at in 2013. So I probably had installed a XDG App / Flatpak version of LibreOffice back then and it kept this isolated profile in ~/.var/app (or the equivalent) all along.

I'm not sure if/how this can be solved, just sharing my insight as a user as to what's probably going on behind the scenes.

**Comment by Erick555** [comment]
Flatpak/xdg-app didn't exist at all in 2013. LO flatpak was published in late 2017 I think.

**Comment by nekohayo** [comment]
Well then, there goes my theory! I have no idea why this flatpak would be inheriting long-gone GTK bookmarks from the 2013 era then. This might be a wider (flatpak) bug but I don't know where to start to investigate it...

**Comment by ssokolow** [comment]
I'd start by running a `grep -R` to figure out where those GTK bookmarks were hiding.
