### ISSUE TITLE
How to add "Arabic" User Interface to my flatpak LibreOffice?

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.libreoffice.LibreOffice#126]
Hi.
I'm Arabic with English as my 2nd tongue. 
My PC locale is set at English USA.

However, I would like to use Arabic UI for LibreOffice that I installed from FlatHub. But when I tried to change language I did not saw "Arabic" option for UI ! Only options for English ! There are "Arabic" options for locale & complex text language, & I set ALL of them to Arabic suadi Arabia & restart LO & retry to see if "Arabic" option appearing to UI. The "Arabic locale" are working very okay, but still no "Arabic" option for UI - kindly see the red arrows in bellow 2 screenshots:

![ui](https://user-images.githubusercontent.com/25375330/90976104-d77dff00-e529-11ea-9ce8-3506a5927697.png)

![ui-options](https://user-images.githubusercontent.com/25375330/90976205-90dcd480-e52a-11ea-8eb3-8d5911ad07a8.png)

I even installed by using "extension manager" Arabic spell checking language & it is working very okay.

Please can you help me how to add "Arabic" user interface to my LO flatpak. This is needed by me not only as personal preference, but to test many bugs related to Arabic UI usage. Currently, I'm unable to test them due to lacking of Arabic user interface .....

**Comment by stbergmann** [comment]
Yes, that's normal.  Such .Locale extensions are only displayed with `flatpak list --all`.

**Comment by Nokia808** [comment]
@stbergmann 
Issue solved ! Thank you for your kind help !

Only one thing I need you to learn me. How can undo the change? I mean how to restore:

org.freedesktop.Platform.Locale//19.08
&
org.libreoffice.LibreOffice.Locale

so that they return to the default state to be corresponding to the locale of operating system as it was originally ? I do not like to apply such revert, but I would like to learn. Kindly, if you cover this point.

**Comment by stbergmann** [comment]
The "obvious" choice should be to deinstall and then install again both org.freedesktop.Platform and org.libreoffice.LibreOffice.  No idea if there is a better way.  You may want to ask e.g. on the flatpak mailing list (see <https://flatpak.org/about/>).

**Comment by Nokia808** [comment]
@stbergmann 
Thank you for help. I contact them.

**Comment by Nokia808** [comment]
@stbergmann 
Hi. I removed these 2 packages then run:
flatpak config --set languages "en;ar"
& finally install them again but I'm still having all locales ! - see the following:
https://github.com/flatpak/flatpak/issues/3816

**Comment by Nokia808** [comment]
@stbergmann 
I solved it by a workaround ! It is due to a bug from flatpak side as they label it.

I solve if by the following workaround:

    remove these 2 packages by run:
    flatpak uninstall org.freedesktop.Platform.Locale//19.08
    &
    flatpak uninstall org.libreoffice.LibreOffice.Locale
    install them again by using --subpath command as following:
    flatpak install --subpath=/en --subpath=/ar flathub org.freedesktop.Platform.Locale//19.08
    &
    flatpak install --subpath=/en --subpath=/ar flathub org.libreoffice.LibreOffice.Locale
    Every think was okay. Libre Office became available only in English & Arabic.
