### ISSUE TITLE
LibreOffice crashes when opening or generating reports

### ISSUE THREAD

**Issue by SwizzleMaster** [flathub/org.libreoffice.LibreOffice#127]
I only noticed after the fact that reports related to the flatpak build of LO should be posted here on github instead.
I'll post the link to the bugzilla here instead of re-writing.
https://bugs.documentfoundation.org/show_bug.cgi?id=135947

I'm using the flatpak version on Fedora 32

**Comment by stbergmann** [comment]
Lets continue here then.  Please describe exactly what you are doing, and describe exactly the failures you observe.

What I can (not) reproduce:  Opening jbdb.odb (attachment 164493 from <https://bugs.documentfoundation.org/show_bug.cgi?id=135947#c0> in the LO 7.0.0.3 Flatpak on Fedora 32, opening "Reports - Auxiliaries: Procedures For Jobs This Week" opens an empty Writer document without a crash.  (Though there are some java.lang.NullPointerException messages printed on stderr.)

**Comment by SwizzleMaster** [comment]
Well, right now it seems to be worse because even opening a writer document results in a crash. But to answer your question, here are the steps for reproducing the behavior:

1. Download that jbdb.odb file
2. Open Libreoffice Base
3. Open Existing
4. Double click on the report to open it

Behaviour: a writer window opens but before it can display the report, the whole application LibreOffice crashes.
Here's a paste of the terminal output.
https://pastebin.com/ehFG43tY

**Comment by stbergmann** [comment]
> Well, right now it seems to be worse because even opening a writer document results in a crash.

Have you tried starting LO in safe mode (either `flatpak run org.libreoffice.LibreOffice --safe-mode` or "Help - Restart in Safe Mode...")?

**Comment by SwizzleMaster** [comment]
A factory reset did the trick. thanks.
This feature should be made more visible to users. perhaps have it as a pop-up tip after a crash. I've been using LO/Open Office since 2009 and never knew about safe-mode.
