### ISSUE TITLE
Wait for a couple of months before landing new major releases

### ISSUE THREAD

**Issue by fabriciojardim** [flathub/org.libreoffice.LibreOffice#128]
Hi

According to the LibreOffice release schedule when a major release is shipped the previous version continues to be supported for a few months until it reaches end of life.

LibreOffice 7.0 for instance was released on August 05 and LibreOffice 6.4 have scheduled patches until October according to this [link](https://wiki.documentfoundation.org/ReleasePlan/6.4) officially reaching end of life by november.

My suggestion for LibreOffice flatpak is to wait just a couple of months before landing new major releases in the future while keep tracking the old version bug fixes.

Ideally this would be accompanied by the creation of a flatpak beta channel  (#75) where the major releases would apear as early as possible allowing the detection of flatpak related bugs.

Perceived benefits:

* Adds a bit more stability to the user experience while keeping it reasonably up to date.
* If beta channel is created people can easily switch between and find any early bugs with no compromises to productivity.

Of course this proposal represents a significant increase in the work of maintainers. That is why I would like to express my apreciation and can only hope that you find a suitable oportunity to implement something like this.

**Comment by stbergmann** [comment]
This is effectively the same request as <https://github.com/flathub/org.libreoffice.LibreOffice/issues/106> "Please provide LibreOffice Still", so I'm going to close this one.
And yeah, it's mostly the additional work that prevented us from implementing that for now.  But thanks for your kind words!
