### ISSUE TITLE
Update runtime to 20.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.libreoffice.LibreOffice#129]

**Comment by stbergmann** [comment]
Is there a org.freedesktop.Sdk.Extension.openjdk11 for the new runtime/sdk now?  That was still missing when I did a beta test build.

**Comment by Erick555** [comment]
No, there isn't. You have to keep pinging maintainer.

**Comment by stbergmann** [comment]
So this blocks on <https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/issues/13> "Add 20.08 branch".

**Comment by stbergmann** [comment]
I'm planing for the scheduled next LO release (7.0.2) to pick this up.

**Comment by stbergmann** [comment]
> I'm planing for the scheduled next LO release (7.0.2) to pick this up.

done
