### ISSUE TITLE
No version information 

### ISSUE THREAD

**Issue by eszlari** [flathub/org.libreoffice.LibreOffice#13]
There's no version information displayed for libreoffice, when using `$ flatpak search` or in software centers. Please add a release entry to the `appdata.xml` file in libreoffice's git repo.

**Comment by stbergmann** [comment]
Fixed upstream with <https://cgit.freedesktop.org/libreoffice/core/commit/?h=libreoffice-6-0&id=22034278a0955f2857ee1eaccdd2318bd9b9065b> "Include <release> in Flatpak appdata.xml".  Will be included in the LO 6.2 flatpak build.

**Comment by stbergmann** [comment]
"[...] in the LO 6.0.2 flatpak build", I meant.

**Comment by stbergmann** [comment]
seen fixed:

> $ flatpak search org.libreoffice.LibreOffice
> Application ID              Version Branch Remotes Description                       
> org.libreoffice.LibreOffice 6.0.2.1 stable flathub The LibreOffice productivity suite
