### ISSUE TITLE
LibreOffice won't customize the mail merge menu.

### ISSUE THREAD

**Issue by noeltheblank** [flathub/org.libreoffice.LibreOffice#132]
Whenever I try to customize the mail merge options the options become corrupted to the point I can't talk anything. I can't even finish my assignment because of this.

**Comment by stbergmann** [comment]
Please explain exactly the steps you are doing in LibreOffice, and what exactly does not work.

**Comment by noeltheblank** [comment]
1. [I open the mail merge wizard.](https://i.imgur.com/URyzFTb.png)
2. [I open the 'Create' thing to edit some of the address info.](https://i.imgur.com/bz8cql8.png)
3. [I click customize.](https://i.imgur.com/Bh7G3ur.png)
4. [I delete or add something.](https://i.imgur.com/W2Yyxna.png)
5. [Corrupted.](https://i.imgur.com/WSLz4pM.png)

I can't type anything in those spaces, so I have to use the preset address blocks for my assignments.

**Comment by stbergmann** [comment]
Thanks for the recipe.  Filed upstream <https://bugs.documentfoundation.org/show_bug.cgi?id=137209> "gtk3: 'New Address List' dialog gets broken", appears not to be Flatpak-specific.
