### ISSUE TITLE
Starting in safe mode, offline help 

### ISSUE THREAD

**Issue by peerwal** [flathub/org.libreoffice.LibreOffice#133]
Hi everybody,

I got two question on the flatpak installation of LibreOffice:

1. How do I start LibreOffice in safe mode?
2. Where do I get the offline help files?

Thanks for your support.

**Comment by stbergmann** [comment]
>     1. How do I start LibreOffice in safe mode?

`flatpak run org.libreoffice.LibreOffice --safe-mode`

>     2. Where do I get the offline help files?

`flatpak install org.libreoffice.LibreOffice.Help` (see <https://www.libreoffice.org/download/flatpak/>)

**Comment by stbergmann** [comment]
> > 2. Where do I get the offline help files?
> > ```
> 
> `flatpak install org.libreoffice.LibreOffice.Help` (see https://www.libreoffice.org/download/flatpak/)

...except that using the offline help appears to be broken at least with latest LibreOffice 7.0.2.2.  I'll have a look later.

**Comment by peerwal** [comment]
Thanks for your comments!

**Comment by stbergmann** [comment]
> > > 1. Where do I get the offline help files?
> > 
> > 
> > `flatpak install org.libreoffice.LibreOffice.Help` (see https://www.libreoffice.org/download/flatpak/)
> 
> ...except that using the offline help appears to be broken at least with latest LibreOffice 7.0.2.2. I'll have a look later.

Works fine when I try it now with latest LibreOffice 7.0.3.1.  Not sure what my issue was when I tried it back then.
