### ISSUE TITLE
fontconfig user configuration

### ISSUE THREAD

**Issue by abakkk** [flathub/org.libreoffice.LibreOffice#136]
The Font Manager application allows you to activate fonts outside `~/.local/share/fonts`. We need to add `filesystem=xdg-config/fontconfig:ro` to the permissions to retrieve them in LibreOffice.

**Comment by salim-b** [comment]
On my system (Ubuntu 20.04), fonts under `/usr/local/share/fonts/` do not show up in the LibreOffice Flatpak apps. Adding `filesystem=xdg-config/fontconfig:ro` (using [Flatseal](https://github.com/tchx84/Flatseal/)) doesn't help. Any ideas?

**Comment by abakkk** [comment]
@salim-b this is another issue. I reproduced it and have no solution.

**Comment by salim-b** [comment]
> @salim-b this is another issue. I reproduced it and have no solution.

Thanks for the confirmation. I've opened a new issue: https://github.com/flathub/org.libreoffice.LibreOffice/issues/137

**Comment by bam80** [comment]
Still not addressed?
@abakkk maybe you could provide the PR then?
