### ISSUE TITLE
FILEOPEN with a non-latin filename (I have tried Greek and Cyrillic) does lead to an error message or a defunct soffice.bin process

### ISSUE THREAD

**Issue by Dennysium** [flathub/org.libreoffice.LibreOffice#139]
Description:
Trying to open a file with a non-latin filename (I have tried Greek and Cyrillic) does lead to an error message or a defunct soffice.bin process. This is on LIbreoffice 7.0.2.2 (Flatpak!) running on Kubuntu 20.04. I have not noticed this with prior versions.
I have observed this with odt, xlsx and dox documents.

Steps to Reproduce:
1.give a file a name using non-latin characters. 
2.Doubleclick in the filmanager to open

Actual Results:
Either:
no feedback, no file opens
error message file xyz does not exist (whereby the actual non-latin characters are replaced by questionmarks)

Expected Results:
File opens

Reproducible: Always

User Profile Reset: No

OpenGL enabled: Yes

Additional Info:
Version: 7.0.2.2
Build ID: 8349ace3c3162073abd90d81fd06dcfb6b36b994
CPU threads: 12; OS: Linux 5.4; UI render: default; VCL: gtk3
Locale: el-GR (el_GR.UTF-8); UI: en-US
Flatpak
Calc: threaded

Also reported here:
https://bugs.documentfoundation.org/show_bug.cgi?id=137502
but seems to not be reproducible on non flatpak version.

**Comment by stbergmann** [comment]
Sounds like some non--UTF-8 locale issue.  In a shell terminal window, what is the output of `locale`, and, while LibreOffice is running and showing the "file xyz does not exist" error message, what is the output of `ps -ef | grep soffice.bin`?

**Comment by Dennysium** [comment]
This is the output of locale

`LANG=el_GR.UTF-8
LANGUAGE=en_US
LC_CTYPE="el_GR.UTF-8"
LC_NUMERIC=el_GR.UTF-8
LC_TIME=el_GR.UTF-8
LC_COLLATE="el_GR.UTF-8"
LC_MONETARY=el_GR.UTF-8
LC_MESSAGES="el_GR.UTF-8"
LC_PAPER=es_ES.UTF-8
LC_NAME=es_ES.UTF-8
LC_ADDRESS=es_ES.UTF-8
LC_TELEPHONE=es_ES.UTF-8
LC_MEASUREMENT=el_GR.UTF-8
LC_IDENTIFICATION=es_ES.UTF-8
LC_ALL=`

And:
`nikolas@PROX15:~$ ps -ef | grep soffice.bin
nikolas   110234  110200  6 17:53 ?        00:00:01 /app/libreoffice/program/soffice.bin --calc /home/nikolas/Downloads/test/?"?????"??????.ods --splash-pipe=5
nikolas   110235  110234  0 17:53 ?        00:00:00 [soffice.bin] <defunct>
nikolas   110259    7760  0 17:53 pts/3    00:00:00 grep --color=auto soffice.bin`

**Comment by stbergmann** [comment]
and the output of `ls /home/nikolas/Downloads/test/*.ods` and of `LC_CTYPE=C ls -b /home/nikolas/Downloads/test/*.ods`?

**Comment by Dennysium** [comment]
nikolas@PROX15:~$ ls /home/nikolas/Downloads/test/*.ods
    /home/nikolas/Downloads/test/τεστακι.ods
    nikolas@PROX15:~$ LC_CTYPE=C ls -b /home/nikolas/Downloads/test/*.ods
    /home/nikolas/Downloads/test/\317\204\316\265\317\203\317\204\316\261\316\272\316\271.ods

**Comment by stbergmann** [comment]
...and one (hopefully) ultimate one, while LibreOffice is showing the error message: `ps -ef | grep flatpak`

**Comment by stbergmann** [comment]
> ...and one (hopefully) ultimate one, while LibreOffice is showing the error message: `ps -ef | grep flatpak`

(but which will probably not reveal anything anyway, as `/usr/bin/flatpak` exec's into `soffice`; I have no idea why your desktop's file manager would apparently expand the `%U` from the `org.libreoffice.LibreOffice.calc.desktop` `Exec=` line into the garbled `/home/nikolas/Downloads/test/?"?????"??????.ods`)

**Comment by Dennysium** [comment]
nikolas@PROX15:~$ ps -ef | grep flatpak
    nikolas     4578    2282  0 09:48 ?        00:00:00 /usr/libexec/flatpak-session-helper
    nikolas     4582    2282  0 09:48 ?        00:00:00 server --sh -n /run/user/1001/.flatpak-helper/pkcs11-flatpak-4578 --providerp11-kit-trust.so pkcs11:model=p11-kit-trust?write-protected=yes
    nikolas     4676    3152  0 09:48 pts/2    00:00:00 grep --color=auto flatpak

**Comment by Dennysium** [comment]
I think I found something more helpful:

    nikolas@PROX15:~/Downloads/test$ flatpak run org.libreoffice.LibreOffice/x86_64/stable ./τεστακι.ods
    (soffice:36): Gtk-WARNING **: 09:53:30.038: Locale not supported by C library.
        Using the fallback 'C' locale.

**Comment by stbergmann** [comment]
> ```
> nikolas@PROX15:~/Downloads/test$ flatpak run org.libreoffice.LibreOffice/x86_64/stable ./τεστακι.ods
> ```
and then LibreOffice shows the same error message?

> ```
> (soffice:36): Gtk-WARNING **: 09:53:30.038: Locale not supported by C library.
>     Using the fallback 'C' locale.
> ```
I _think_ that GTK warning is unrelated and harmless (but may misremember).  What you may want to do anyway, though, is to make sure that the relevant `.Locale` extensions are not only installed partially; something like `flatpak install --reinstall org.freedesktop.Platform.Locale//20.08`, `flatpak install --reinstall org.libreoffice.LibreOffice.Locale`.

**Comment by Dennysium** [comment]
> and then LibreOffice shows the same error message?
yes

> What you may want to do anyway, though, is to make sure that the relevant .Locale extensions are not only installed partially; something like flatpak install --reinstall org.freedesktop.Platform.Locale//20.08, flatpak install --reinstall org.libreoffice.LibreOffice.Locale.

THANK YOU! This solved the issue!
