### ISSUE TITLE
On KDE Neon 5.21.4, org.libreoffice.LibreOffice 7.1.2.2 want a dependency that is at End of Life

### ISSUE THREAD

**Issue by aer0usa** [flathub/org.libreoffice.LibreOffice#149]
Hi, on KDE Neon 5.21.4, running 'flatpak update' updates org.libreoffice.LibreOffice 7.1.2.2 with flatpak 1.6.5-0ubuntu0.2 gives the following:
```
Info: org.freedesktop.Platform is end-of-life, with reason: The Freedesktop 1.6 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported runtime.
```
And updating LO by itself:
```
$ flatpak update org.libreoffice.LibreOffice
Looking for updates…


        ID                                Branch          Op          Remote           Download
 1. [✗] org.freedesktop.Platform          20.08           u           flathub          1.0 kB / 267.9 MB

Warning: Error deploying: Failed to read commit a4f37bb933cf4792d472db2055886427d55074cdaf5bd8e4397dc3e2bc0305e1: No such metadata object 193172d8706f5acdb868193aa49b838973160bd9b9148b28a2b83f848e9f3503.dirtree
Updates complete.
```

I didn't see an issue for this, so I'm passing it along.

Thank you!

**Comment by stbergmann** [comment]
The LibreOffice flatpak is not using the outdated freedesktop 1.6 runtime for quite a while now.  No idea why you are getting that first info message.
And no idea about the second warning message, either.  Does it nevertheless install the latest LibreOffice 7.1.2.2 flatpak (at least when you maybe issue another `flatpak update` request)?

**Comment by aer0usa** [comment]
Interesting. And my apologies, now I see that LO uses org.freedesktop.Platform 20.08, and another flatpak I am using uses 1.6.

Yes, the LibreOffice 7.1.2.2 flatpak itself installs, updates, and runs with no problem.

It appears that org.freedesktop.Platform 20.08 is having problems updating, but that isn't your fault.

My apologies, and thank you for your quick reply. I'll close this issue.
