### ISSUE TITLE
New Screenshots

### ISSUE THREAD

**Issue by Byrdg** [flathub/org.libreoffice.LibreOffice#166]
Hi, I have these screenshots (attached) that I think is better than the current one because as they are a little bit more updated. if its OK to update the screenshots, Can you please point me to the appdata XML source?"

![Screenshot from 2021-11-08 15-27-38](https://user-images.githubusercontent.com/94136706/141363828-f322e36b-5248-45ea-8856-8830700e099d.png)
![Screenshot from 2021-11-08 15-24-54](https://user-images.githubusercontent.com/94136706/141363795-70b48154-e540-46cb-a7b1-90e605fdf080.png)
![Screenshot from 2021-11-08 15-25-49](https://user-images.githubusercontent.com/94136706/141363803-66a8fd73-d29c-44b4-8b9e-d2c69a18e8db.png)
![Screenshot from 2021-11-08 15-26-20](https://user-images.githubusercontent.com/94136706/141363806-4a26a024-6a59-4ec7-b656-75e6b2125330.png)

**Comment by stbergmann** [comment]
The screenshots used by the LibreOffice Flatpak build are the same that are used upstream, see the links at <https://git.libreoffice.org/core/+/61c4112dc3d65800a8217591c9828fae918834d9/solenv/bin/assemble-flatpak-appdata-step1.sh#21>.  If you want to change those screenshots, please take that upstream to <https://www.libreoffice.org/community/get-involved/>.
