### ISSUE TITLE
Libreoffice doesn't update with flatpack?

### ISSUE THREAD

**Issue by DiploMaths** [flathub/org.libreoffice.LibreOffice#192]
HEllo,

I'm new to flatpack, and I'm lost...

On the libreoffice website, the latest stable for Linux  is 7.3.5. (https://fr.libreoffice.org/download/telecharger-libreoffice/)

On flathub it is 7.3.5.2, that seems quite normal... (https://flathub.org/apps/details/org.libreoffice.LibreOffice)

But in my appstore, the latest flat version is 7.3.3.2.

How could I get the latest ?

More over... How could it be automatic, so that I don't have to check the latest versions...

I use a laptop with Mint 20.3, and flat is supposed to need nothing from me (according to the site faltpack.org).

Thank you very much for your help ! :D

**Comment by stbergmann** [comment]
> But in my appstore, the latest flat version is 7.3.3.2.

whatever your appstore is?

**Comment by DiploMaths** [comment]
Oh the base appstore of linux ubuntu I guess. In french it's called "Logiteque".
It's like an appstore, it's build in Mint 20.3 LTE.

**Comment by stbergmann** [comment]
No idea about that.  You probably better contact whoever runs that appstore, then.

Closing this as, as you say, <https://flathub.org/apps/details/org.libreoffice.LibreOffice> correctly offers the latest LibreOffice 7.3.5.
