### ISSUE TITLE
Impress don't insert a video

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.libreoffice.LibreOffice#20]
Libreoffice Impress load the video but can not to reproduce it

**Comment by stbergmann** [comment]
I cannot reproduce your problem, with current LO 6.0.1 flatpak running on Fedora 27/GNOME.  Downloaded <http://downloads.xiph.org/video/A_Digital_Media_Primer_For_Geeks-360p.webm>, then in LO Impress inserted it on a slide (via "Insert - Audio or Video...").  Playback works, and still works after saving and re-opening the .odp document (and also works in full-screen slide show mode).
Please be more precise what exactly does not work for you, in which environment.

**Comment by Lvaskz** [comment]
Greetings, I'm in linuxmint 18.3, 64 bits, cinnamon. I tried to insert a video with mp4 extension on a slide. The fact is that it inserts it, but as an audio, you can not visualize the video, but the audio. I did the test with libreoffice appimage and it did not present any problem, the video is loaded and it plays well.

**Comment by stbergmann** [comment]
Indeed.  Downloaded <http://techslides.com/demos/sample-videos/small.mp4>.  After installing gstreamer1-libav-1.12.4-1.fc27.x86_64 from rpmfusion.org, the "repo-native" LO in Fedora 27 played the video.  But the flatpak'ed LO shows just an audio icon.
I assume what is available on the host is irrelevant, and the flatpak just has available what is packaged in the underlying org.gnome.Platform runtime.

**Comment by stbergmann** [comment]
seen working in LO 6.0.2 flatpak
