### ISSUE TITLE
Doesnt remember last edit position

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.libreoffice.LibreOffice#208]
Writer is supposed to skip to the point where the user edited last time. That doesnt happen using the Flatpak.

**Comment by stbergmann** [comment]
I assume this is not specific to the Flatpak version of LibreOffice, but is rather the general issue discussed at <https://bugs.documentfoundation.org/show_bug.cgi?id=141586> "Restoring last document position is unreliable".
