### ISSUE TITLE
Question: Why a gdrive client and password client during build??

### ISSUE THREAD

**Issue by Ratatouilledummie** [flathub/org.libreoffice.LibreOffice#210]
in script build define during build a  
"--with-gdrive-client-id=280867422816-9jc83t6phkfb2q8p94dtk8kr5fa8af3r.apps.googleusercontent.com --with-gdrive-client-secret=Hnzikj7HqdqsUYLru4jmFo1p","
why this definition?? it's a Google Cloud API??? sorry i don't undestand. in the build docs not have a reference.
this look's necessary to build but how it's work?

**Comment by stbergmann** [comment]
see <https://github.com/flathub/org.libreoffice.LibreOffice/commit/be6299e85060e5c7fd7f9f142da775efeea1863d> "Support for Google Drive"
