### ISSUE TITLE
Document whether donation nag bar is present

### ISSUE THREAD

**Issue by ssokolow** [flathub/org.libreoffice.LibreOffice#220]
Currently, despite using Flatpak everywhere else I feasibly can (if for no other reason, for how easy it makes it to customize sandboxing without breaking things), I avoid using the Flathub release of LibreOffice because both I and [the blog post I learned from](https://www.remembertheusers.com/2019/11/0580-libreoffice-nag-notices.html) failed to patch out the donation nag ([apparently](https://ask.libreoffice.org/t/howto-disable-libreoffice-donations-banner/63169) more correctly called an "InfoBar") in any manner accessible through user-scoped means.

Specifically, for the distro-packaged version, to have any effect, we had to create a new file in `$BASEDIR/share/registry`, which would be read-only and under `/app` in the Flatpak, containing the following:

    <?xml version="1.0"?>
    <oor:data xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oor="http://openoffice.org/2001/registry">
      <dependency file="main" />
      <oor:component-data xmlns:install="http://openoffice.org/2004/installation" oor:name="Setup" oor:package="org.openoffice">
        <node oor:name="Product">
          <prop oor:name="LastTimeGetInvolvedShown" oor:op="fuse" oor:finalized="true">
            <value>0</value>
          </prop>
          <prop oor:name="LastTimeDonateShown" oor:op="fuse" oor:finalized="true">
            <value>0</value>
          </prop>
        </node>
      </oor:component-data>
    </oor:data>

Could you please document whether the donation nags have been patched out in the Flatpak release to resolve this "uncertain, so assume unacceptable" situation?

(I have a zero-tolerance policy for panhandling or advertising outside my web browser. My desktop is my sanctuary.)

**Comment by stbergmann** [comment]
> Could you please document whether the donation nags have been patched out in the Flatpak release

It has not been patched out.

**Comment by ssokolow** [comment]
Any chance you could document it somewhere more discoverable than a closed GitHub issue?
