### ISSUE TITLE
Flatpak shuts down after a few seconds

### ISSUE THREAD

**Issue by CodeSandwich** [flathub/org.libreoffice.LibreOffice#249]
Running LO flatpak results in a silent crash after a few seconds no matter what I'm doing.

(Sorry for poor formatting, I'm using oh-my-bash, ` ~  ` is my prompt, ` ~  137 ` is my prompt with an exit status, in this case `137`)

For example, trying to run LO normally:
```
 ~  flatpak run org.libreoffice.LibreOffice
Failed to open display
 ~  137 
```
There are no artifacts on the screen, LO seems to work just fine for a few seconds and then it shuts down.

Interestingly you don't even need to run LO in LO container:
```
 ~  flatpak --command=sh run org.libreoffice.LibreOffice
[📦 org.libreoffice.LibreOffice ~]$  ~  137 
```
It too works perfectly fine for a few seconds executing commands, and then it shuts down regardless of what I'm doing. The only difference is that it seems to break the output of the terminal, I can't see what I'm typing anymore, but otherwise it works fine, tested on Konsole, XTerm, Bash with oh-my-bash and sh:
```
 ~  137  
bash: asfd: command not found
 ~  127  
abcd
 ~  
```
The `abcd` comes from typing blindly `echo abcd`.

I'm running Flatpak 1.15.4 on Manjaro with KDE 5.27.6 on Wayland. It's been like this for months, but I was too lazy to investigate more, I just kept using the native version of LO.

**Comment by stbergmann** [comment]
> Interestingly you don't even need to run LO in LO container:

Does that crash also happen when you run just the underlying runtime instead of the LO app, i.e., `flatpak run --command=sh org.freedesktop.Platform//22.08`?

**Comment by CodeSandwich** [comment]
> `flatpak run --command=sh org.freedesktop.Platform//22.08`

It doesn't crash. I'm using several other apps as flatpaks and they too all work fine, only the LO crashes.

**Comment by CodeSandwich** [comment]
Thank you @xalt7x, that was it! After running this command LO works perfectly fine, it doesn't shut down anymore.

This is a KDE problem, so I'll close this issue, there's nothing to fix in this package.
