### ISSUE TITLE
Error when opening files on a SAMBA share (Plasma Desktop) 

### ISSUE THREAD

**Issue by chrisHRD** [flathub/org.libreoffice.LibreOffice#257]
**Issue**
When LibreOffice is installed via Flathub's flatpak, the application is unable to properly open documents, spreadsheets, presentations, etc... over an SMB server connection when selected via KDE Plasma Desktop's file manager (Dolphin). An error is provided on screen about the file being locked and unable to be opened. Screenshot provided below. This issue applies to all remote LibreOffice files. The native packages of LibreOffice found on Fedora or Debian do not have this issue (when used in conjunction with the Plasma Desktop and its file manager). 

This provides a challenge on systems where the Flatpak is the primary offering of LibreOffice, namely Fedora Kinoite and SteamOS.

_Sidenote: when using distrobox to install the DEB variant of LibreOffice on an immutable OS like Fedora Kinoite, the native package is able to open remote SMB files via Fedora's native Dolphin._ 

**Related Issues**
[Issue 175](https://github.com/flathub/org.libreoffice.LibreOffice/issues/175)

**LibreOffice Details**
- Version: 7.6.0.3 (X86_64) / LibreOffice Community
- Build ID: 69edd8b8ebc41d00b4de3915dc82f8f0fc3b6265
- CPU threads: 4; OS: Linux 6.4; UI render: default; VCL: gtk3
- Locale: en-US (en_US.UTF-8); UI: en-US
- Flatpak
- Calc: threaded

**System Details**
- Operating System: Fedora Linux Kinoite 38
- KDE Plasma Version: 5.27.7
- KDE Frameworks Version: 5.109.0
- Qt Version: 5.15.10
- Kernel Version: 6.4.15-200.fc38.x86_64 (64-bit)
- Graphics Platform: Wayland

**Screenshot**
![image](https://github.com/flathub/org.libreoffice.LibreOffice/assets/32101046/9944552a-d83b-4227-a92e-3eb4a97b4f8c)

**Comment by stbergmann** [comment]
Did this only start to happen right now after an update of the LibreOffice flatpak?  What is the output of a `flatpak info org.libreoffice.LibreOffice` command line?

**Comment by chrisHRD** [comment]
@stbergmann 

Hello, This has been occurring to me since I moved over to the Flatpak version around version 7.4 (I believe). I migrated to Fedora Kinoite 38 for my work machine. When trying to manipulate documents on our company's Debian SAMBA Server, I discovered this issue with the flatpak (as well as the absence of the KDE file I/O dialogs). 

On Fedora KDE Spin, using the native `libreoffice-kf5` package, this issue does not occur. For testing I added the native `libreoffice-kf5` package via distrobox on Fedora Kinoite and things works as expected. So I guess we can rule out the base OS.

**Output of `flatpak info org.libreoffice.LibreOffice`**
```
LibreOffice - The LibreOffice productivity suite
ID: org.libreoffice.LibreOffice
Ref: app/org.libreoffice.LibreOffice/x86_64/stable
Arch: x86_64
Branch: stable
Version: 7.6.0.3
License: MPL-2.0
Origin: flathub
Collection: org.flathub.Stable
Installation: system
Installed: 762.8 MB
Runtime: org.freedesktop.Platform/x86_64/22.08
Sdk: org.freedesktop.Sdk/x86_64/22.08
Commit: 6c3f27e3e799f225353681ce279c6a49b3b48c628e5dd9bfb91514654fa318af
Parent: 517ef7e1340a998b01af8b1ab129677b874ab593a2fcc75414d2460be8700c00
Subject: Update gvfs-1.50.6.tar.xz to 1.52.0 (c4535c99)
Date: 2023-09-18 08:54:18 +0000
```

**Comment by zhenyakoltsov** [comment]
I confirm the presence of this problem. I use Debian and Flatpak, when I open a document from the network (smb) I get the same message.
LibreOffice version 7.6.2.1

**Comment by eszlari** [comment]
Can confirm on Kubuntu 23.10.

**Comment by chrisHRD** [comment]
Can confirm it is possible to "open" LibreOffice documents on a Samba server on Fedora 40 with Plasma 6.2 via Dolphin; however, you cannot save back to the file server in a new location because the Save-As-Dialog is the GTK one. I'm going to close this issue now and look to see if the Save-As-Dialog issue is reported elsewhere.

```
flatpak info org.libreoffice.LibreOffice

LibreOffice - The LibreOffice productivity suite

          ID: org.libreoffice.LibreOffice
         Ref: app/org.libreoffice.LibreOffice/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 24.8.2.1
     License: MPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 792.1 MB
     Runtime: org.freedesktop.Platform/x86_64/24.08
         Sdk: org.freedesktop.Sdk/x86_64/24.08

      Commit: 6ff3bbbfb9ba060296d9a31fa3d34ceba4651995dc69f12fed36eb1bd15ade6c
      Parent: a711d6ca68bc4063d09fd87720b8b5c879f1c95d50303046c381afcd51dcf0b6
     Subject: Update to libreoffice-24.8.2.1 (d9ca3696)
        Date: 2024-09-27 09:33:09 +0000

```
