### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by julianfairfax** [flathub/org.libreoffice.LibreOffice#259]
The `host` permission is quite vast.  Why does it need access to the entire filesystem? As far as I'm aware, it can access any file through a portal. It doesn't need constant access to a user's system?

**Comment by Erick555** [comment]
Did you actually test it? LO doesn't use portals.

**Comment by julianfairfax** [comment]
I have tested it. It appears everything opens as read-only. Am I correct in assuming portals would have to be implemented by the LO developers (and thus we can close this issue for now)?

**Comment by Erick555** [comment]
Yes, portals need to be implementd by LO devs first.

**Comment by julianfairfax** [comment]
Closing until then
