### ISSUE TITLE
Cannot update LibreOffice:  Corrupted file object

### ISSUE THREAD

**Issue by Vinnl** [flathub/org.libreoffice.LibreOffice#262]
When I try to update the LibreOffice Flatpak (from 7.6.1.2 to 7.6.2.1), I get:

<pre><code>$ flatpak update org.libreoffice.LibreOffice
Looking for updates…

<b>        ID                           Branch  Op  Remote   Download</b>
 1. [✗] org.libreoffice.LibreOffice  stable  u   flathub  3.5 MB / 315.0 MB

Error: While pulling app/org.libreoffice.LibreOffice/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected=&apos;4819e24d237f7948e55da4ff82ceaabccc9dcad0f57bd0a1b8f87fddcab36517&apos; actual=&apos;698e6e342789a38fb96f8f1644053644a2e4e1aeba4127b5d8954ed43ed063c4&apos;
Updates complete.
<span style="color:#C01C28"><b>error: </b></span>There were one or more errors
</code></pre>

**Comment by Vinnl** [comment]
I worked around this by uninstalling and re-installing LibreOffice, which succeeded. I see now that the command `flatpak repair` might have worked as well.

**Comment by stbergmann** [comment]
No idea what exactly happened there, but doesn't appear to be a general issue.  Closing for now, assuming it was some sort of temporary hickup.
