### ISSUE TITLE
Error when saving files on a SAMBA share after update

### ISSUE THREAD

**Issue by mmuir-ca** [flathub/org.libreoffice.LibreOffice#276]
### Issue
After updating via Flatpak, the application is no longer able to save documents that reside on a Samba drive (mount via CIFS).  You can create a new document and save it to the network drive however once saved, you are no longer able to save any more edits. 
Downgrading to the previous version solves the problem. This was tested on two different computers to confirm that the update caused the issue.

The error produced was the following:
> Error saving the document test1:
> Error creating object.
> Could not create backup copy.

### Libreoffice details:
```
~$ flatpak remote-info --log flathub org.libreoffice.LibreOffice
        ID: org.libreoffice.LibreOffice
       Ref: app/org.libreoffice.LibreOffice/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 314.3 MB
 Installed: 765.7 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: 361dde051c7d4e5ba3b1d1c5fd839ae64b51f6f73fe32859c009e6edef2c4d36
    Parent: 9024d8a206aeca0a1473e7437fc638186dea0aef2091a05ffea0b61f168f4d36
   Subject: Update to libreoffice-24.2.0.3 (c019e623)
      Date: 2024-01-31 09:07:23 +0000
   History: 

    Commit: 9024d8a206aeca0a1473e7437fc638186dea0aef2091a05ffea0b61f168f4d36
   Subject: Update gvfs-1.52.1.tar.xz to 1.52.2 (#272) (d9e2f088)
      Date: 2024-01-08 13:38:49 +0000
```
### System details:
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.6.10-76060610-generic 
Packages: 3668 (dpkg), 29 (flatpak),  
Shell: bash 5.1.16 
DE: GNOME 
WM: Mutter 
WM Theme: Pop 
CPU: Intel i7-10750H (12) @ 5.000GHz 
GPU: NVIDIA GeForce GTX 1660 Ti Mobil 
GPU: Intel CometLake-H GT2 [UHD Graph 
Memory: 7229MiB / 64164MiB

**Comment by heliconz** [comment]
Can I add a +1 to this? Everything exactly as @mmuir-ca commented - I've confirmed this on two different systems, one with RHEL 9 and one with Clear Linux.

The latest version [Subject: Try to appease Flathub linter (61ad9b1d) | Date: 2024-02-29 15:23:07 +0000] still exhibits this bug and it's a blocker as it makes Libreoffice completely unusable in that no documents stored on an smb share can be edited.

![image](https://github.com/flathub/org.libreoffice.LibreOffice/assets/152485521/5127e656-34ec-4a33-8c85-208f801c9239)

**Comment by stbergmann** [comment]
lets see whether <https://git.libreoffice.org/core/+/a8814b5921676b1c01a19b0af243712c55fb0307%5E!/> "[tdf#55004](https://bugs.documentfoundation.org/show_bug.cgi?id=55004) Fix backup copy creation for files on mounted samba shares" will make a difference in a future LO 24.2.3 flathub build

**Comment by mmuir-ca** [comment]
I can confirm that libreoffice-24.2.2.2 fixes the issue which is a great.
``~$ flatpak info org.libreoffice.LibreOffice

The Document Foundation - The LibreOffice productivity suite

          ID: org.libreoffice.LibreOffice
         Ref: app/org.libreoffice.LibreOffice/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 24.2.2.2
     License: MPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 768.8 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 31f99f9724876260827a26744d3a867a134d65b758092e6301956574e1d1f106
      Parent: ef0daf3284c065a22ea4a88a4304979c4960c27c67670acdb1b6d8d18f7d2fb3
     Subject: Update to libreoffice-24.2.2.2 (0c0a883e)
        Date: 2024-03-28 21:57:09 +0000
`

```
