### ISSUE TITLE
LibreOffice crashed with "javaldx failed".

### ISSUE THREAD

**Issue by pthfdr-42** [flathub/org.libreoffice.LibreOffice#29]
When launching, a "Fatal Error" dialog popped up, and LibreOffice crashed after clicking "OK":

    The application cannot be started.
    User installation could not be completed.
Console output:

    pthfdr:/u/h/pthfdr> flatpak run org.libreoffice.LibreOffice
    javaldx failed!
    Warning: failed to read path from javaldx
    
    ** (soffice:15): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
    Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by stbergmann** [comment]
What Linux distro are you using?

What is the output of `flatpak list -vv` and `flatpak info -vv org.libreoffice.LibreOffice`?

Is the LO flatpak able to create and write to ~/.var/app/org.libreoffice.LibreOffice/config/libreoffice/4/user/?  What is the output of `flatpak run -vv org.libreoffice.LibreOffice`?

**Comment by pthfdr-42** [comment]
[Here is the output.](https://github.com/flathub/org.libreoffice.LibreOffice/files/1942978/OUTPUT.txt)
I am using the System V init.I am not a member of the cult of `systemd`.

**Comment by stbergmann** [comment]
"F: skipping export for path /usr/home/pthfdr/.var/app/org.libreoffice.LibreOffice" <- I guess that is what causes LO to fail; it wants to create ~/.var/app/org.libreoffice.LibreOffice/config/libreoffice/4/user/ and at least the "javaldx failed!" stderr output and "Fatal Error" dialog indicate that there's problems doing so.

No idea whether "F: Failed to run in transient scope: No systemd user session available, cgroups not available" is relevant here, or whether the root cause is something else.

@alexlarsson: any idea?

**Comment by pthfdr-42** [comment]
But, I think that you should constraint LibreOffice to `~/.local`.  
Seriously, too many programs are pooping my home directory because that they do not care.

    pthfdr:uh/pthfdr> ls -Falish
    total 11K
     1617 1.0K drwx------  3 pthfdr users 1.0K Apr 24 23:07 ./
     1610 1.0K drwxr-xr-x  4 root   root  1.0K Jan 14 20:12 ../
     1625 1.0K drwx------ 16 pthfdr users 1.0K Apr 24 15:18 .config/
     1618    0 lrwxrwxrwx  1 pthfdr users    8 Sep 27  2017 .cache -> /run/shm/
     1619    0 lrwxrwxrwx  1 pthfdr users    7 Mar 15 19:40 .dbus -> .config/
     1620    0 lrwxrwxrwx  1 pthfdr users   13 Oct 20  2017 .gnupg -> .config/gnupg/
    30929 6.0K -rw-------  1 pthfdr users 5.8K Mar 12 12:14 .gtkrc-2.0
     1621    0 lrwxrwxrwx  1 pthfdr users    7 Oct 20  2017 .local -> .config/
     1624 1.0K -rw-------  1 pthfdr users  559 Apr 23 23:13 .mkshrc
     1622    0 lrwxrwxrwx  1 pthfdr users    7 Oct 20  2017 .pki -> .config/
    14562    0 lrwxrwxrwx  1 pthfdr users   14 Apr 24 12:29 .tixati -> .config/tixati/
    14564 1.0K -rw-------  1 pthfdr users  103 Apr 24 10:26 .Xauthority
    22743    0 lrwxrwxrwx  1 pthfdr users    9 Mar 16 23:59 .xsession-errors -> /dev/null

**Comment by stbergmann** [comment]
Note that ~/.var/app/org.libreoffice.LibreOffice/config is what the Flatpak infrastructure passes to the running LO flatpak for XDG_CONFIG_HOME (and which the latter thus uses).

**Comment by pthfdr-42** [comment]
I think that it is a problem with Flatpak itself [since similar errors happened with Steam.](https://github.com/flathub/org.libreoffice.LibreOffice/files/1945414/1.txt)

**Comment by barthalion** [comment]
Transient scope message is not a fatal error. Looks similar to problems people had with symlinking their /home to other locations (which seems to be the case here?). Either way, please report it against flatpak repository, it's not related to LibreOffice.

**Comment by pthfdr-42** [comment]
I placed the home directories under /usr/home.It is not a symlink.
