### ISSUE TITLE
Greyed out Embedded Options under Options->Load/Save->MIcrosoft only in the flatpak version

### ISSUE THREAD

**Issue by n3thshan** [flathub/org.libreoffice.LibreOffice#301]
### Info
 Version: 24.8.0.3 (X86_64) / LibreOffice Community
Build ID: 0bdf1299c94fe897b119f97f3c613e9dca6be583
CPU threads: 8; OS: Linux 6.10; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Flatpak
Calc: threaded 

### Issue
The options under this which should be editable are not. For example SmartArt cannot be checked on/off. A screenshot is provided below. This is purely a flatpak problem as the distro package allowed me to edit those. Please consider this issue. Thank you!

![Screenshot from 2024-08-27 07-51-01](https://github.com/user-attachments/assets/66f2e13a-7fe0-438b-89d4-843e2e2f83db)

**Comment by n3thshan** [comment]
Here are some further screenshots of flatseal permissions: 
![Screenshot from 2024-08-27 18-06-07](https://github.com/user-attachments/assets/03d41d44-be79-4f88-9272-312b1247155a)
![Screenshot from 2024-08-27 18-06-18](https://github.com/user-attachments/assets/d3bb301e-c026-4696-a62d-c1325cdfea0a)
![Screenshot from 2024-08-27 18-06-31](https://github.com/user-attachments/assets/0a778a78-08fd-4475-8ace-7be919e6523e)
![Screenshot from 2024-08-27 18-06-41](https://github.com/user-attachments/assets/f99fad00-1d81-4ad8-a345-d46fbdf07a05)
![Screenshot from 2024-08-27 18-06-56](https://github.com/user-attachments/assets/4027707b-47fb-42d0-a70e-001ebf080786)

**Comment by stbergmann** [comment]
"For example SmartArt cannot be checked on/off. [...] This is purely a flatpak problem as the distro package allowed me to edit those."

Checking e.g. "SmartArt to LibreOffice shapes or reverse" on/off there doesn't work for me in other non-flatpak Linux builds, either.  Checked both a `libreoffice-core-24.2.5.2-2.fc40.x86_64` Fedora 40 version and a local master (towards LO 25.2) developer build.  What is your distro package?

**Comment by n3thshan** [comment]
The issue does not appear to be a flathub only one. There has been another who reported today that the same issue persists when built from sources in Debian. Thus im closing this issue.
