### ISSUE TITLE
LibreOffice flatpak no longer follows system-wide GTK theme

### ISSUE THREAD

**Issue by juxi500** [flathub/org.libreoffice.LibreOffice#31]
Hello,

I noticed that around update to LibreOffice 6.0.2.x flatpak, LibreOffice stopped following my system-wide GTK theme. I use adwaita-dark on Gnome 3.22 on EL7.4 flatpak ver. 0.8.7. Before that update everything was great, LibreOffice was dark-themed and looked like the rest of my apps. But now it is using adwaita-light. All other flatpak applications are working fine and using adwaita-dark so I think this is probably LibreOffice specific bug.

Have a nice day :)

**Comment by TingPing** [comment]
Theming is identical between both runtimes.

**Comment by juxi500** [comment]
The problem is still present after today's update

**Comment by stbergmann** [comment]
@ramcq, seems to be fallout from the GNOME to freedesktop.org runtime change. I can reproduce this too, and when I roll back to before <https://github.com/flathub/org.libreoffice.LibreOffice/commit/7a2393f5fcab8c6938180c4718f2c61acd495528> "port to freedesktop.org 1.6 runtime" everything is fine again.

**Comment by nedrichards** [comment]
@stbergmann @ramcq is currently on paternity leave but I know he's hacking a bit at odd hours so I'll make sure he sees this. Please don't just revert the FDo change though - it would have an impact on the Endless OS release process that can be managed but unexpected breakage would be... unexpected.

**Comment by juxi500** [comment]
After last few updates the issue is still present.

**Comment by brittyazel** [comment]
Can confirm that with libreoffice 6.1, the flatpak version STILL doesn't follow system-wide GTK theming

**Comment by MatMaul** [comment]
Same here, still not working. `gsettings get org.gnome.desktop.interface gtk-theme` inside the flatpak bundle give me a correct `Adwaita-dark`, no idea why this is still not working.

**Comment by LordMethenor** [comment]
Same. I'm on an ARM chromebook, and flatpak is the only working way for me to get libreoffice 6.1.

**Comment by stbergmann** [comment]
Tried again with local builds of upcoming LO 6.2 (which got rebased to org.freedesktop.Platform//18.08):  The build as-is, based on org.freedesktop.Platform//18.08, still doesn't honour setting the system-wide theme (with GNOME's Tweaks tool) to Adwaita-dark.  But an experimental build based instead on org.gnome.Platform//3.30 (which reportedly is in turned based on org.freedesktop.Platform//18.08) _does_ honour the setting correctly.
@ramcq, do you think you could find time to look into this again?

**Comment by ramcq** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/elements/desktop/gsettings-desktop-schemas.bst is what fd.o 18.08 has, and https://gitlab.gnome.org/GNOME/gnome-build-meta/blob/gnome-3-30/elements/sdk/gsettings-desktop-schemas.bst is what GNOME 3.30 has. I don't understand what there would affect whether the settings are visible to LO or not, if the rest is the same...

**Comment by abderrahim** [comment]
The problem is not with gsettings. The settings are set correctly inside the sandbox.

The problem is with the availability of the theme itself inside the sandbox. It seems the freedesktop sdk (both 1.6 and 18.08) don't provide Adwaita-dark, while gnome 3.30 does.

**Comment by ramcq** [comment]
So this is down to https://gitlab.gnome.org/GNOME/gnome-themes-extra/tree/master being present in the GNOME runtime but not in the fd.o one? Particularly having the dark version of Adwaita installed under a different name, so this bug is specific to users of Adwaita-dark. AFAIK the documented/supported way to enable dark Adwaita desktop-wide is using the gtk-application-prefer-dark-theme Gtk+ setting, and having your theme set to Adwaita-dark is a legacy thing.

That said, there is _almost_ nothing in this theme for gtk+3.0:
```
ramcq@upsilon:/usr/share/themes/Adwaita-dark$ ls
gtk-2.0  gtk-3.0  index.theme
ramcq@upsilon:/usr/share/themes/Adwaita-dark$ cat gtk-3.0/gtk.css 
@import url("resource:///org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css");
```

Maybe we should just ship it. :P

**Comment by javacraft** [comment]
I can confirm that as of:

- LibreOffice Version 6.2.0.3
- Build ID:  `98c6a8a1c6c7b144ce3cc729e34964b47ce25d62`
- OS: CentOS Linux release 7.6.1810
- Kernel: 3.10.0-957.5.1.el7.x86_64

its flatpak still does not follow system GTK Theming; yet the same AppImage does.

**Comment by PranavBhattrai** [comment]
> ```
> flatpak install flathub org.gtk.Gtk3theme.Breeze-Dark
> ```

what is after "=stable..." ? What are those 3 dots for?

**Comment by MatMaul** [comment]
it seems to be solved ?

**Comment by abderrahim** [comment]
Indeed, Adwaita-dark is now available [on flathub](https://github.com/flathub/org.gtk.Gtk3theme.Adwaita-dark).

**Comment by MatMaul** [comment]
Oh indeed and it auto install so I didn't even notice :)
