### ISSUE TITLE
Provide Fresh and Still versions

### ISSUE THREAD

**Issue by eszlari** [flathub/org.libreoffice.LibreOffice#33]

**Comment by stbergmann** [comment]
@alexlarsson, would there even be a way to provide different versions of LO simultaneously on flathub?

**Comment by nedrichards** [comment]
Not currently, no. Multiple simultaneous releases per application is complexity that we don't need right now. You may remember that during the initial LO PR we talked about this and came to the understanding that whatever the LibreOffice upstream considered to be 'stable' should be stable for the purposes of flathub (e.g. we were fine with fresh, the policy isn't about having needlessly old software, just good software).

**Comment by eszlari** [comment]
I think there is a reason that upstream maintains these two branches: people do serious work with libreoffice. At the moment I need it for import work and I'm reluctant to change the major version in the middle of a project (I started with 5.4).
