### ISSUE TITLE
Add integrated LibreOffice Help offline

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.libreoffice.LibreOffice#35]

**Comment by stbergmann** [comment]
There is currently work going on in LO upstream for a new offline html help format, which will use an external web browser to display the help content.  My plan is to wait for that, and then include that in the LO flatpak (maybe for LO 6.1).

**Comment by LeandroStanger** [comment]
I upgraded LibreOffice to version 6.1.0.3 and offiline help has not been included yet
![captura de tela de 2018-08-12 20-07-41](https://user-images.githubusercontent.com/26097419/44007606-1f2d11dc-9e6f-11e8-8aa1-b9f5681db54d.png)

**Comment by stbergmann** [comment]
Yes, "maybe for LO 6.1" didn't work out in the end.  Stay tuned :)

**Comment by stbergmann** [comment]
Looking into using LO upstream --with-help=html (i.e., the new locally bundled HTML-based help content, to be viewed in an external browser) in the LO flatpak build, I find multiple issues:
First, the help system relies on URIs with query parts (e.g., <file:///.../program/../help/index.html?Target=swriter/sfx/ui/startcenter/open_all&Language=en-US&System=UNIX&Version=6.3>).  However, per <https://tools.ietf.org/html/rfc8089> "The 'file' URI Scheme", file URIs appear to not support a query (nor a fragment) part (I've written to the email address given at <https://www.rfc-editor.org/info/rfc8089> seeking clarification of this).  While contemporary browsers are apparently capable of handling a query part in a file URI, implementations of at least LibreOffice itself (e.g., Translator::translateToExternal in stoc/source/uriproc/ExternalUriReferenceTranslator.cxx, turning a query part's leading "?" in the input into an escaped "%3F" in the output) and of xdg-open (used by LibreOffice on Unix-like systems to open a URI in an external browser; e.g., the /usr/bin/xdg-open in current org.freedesktop.Platform/x86_64/18.08 apparently treats a query part as part of the encoded file system pathname, and apparently drops a fragment) are not.
Therefore, LibreOffice wraps these file URIs with query parts into temporary HTML files, and instead passes the file URIs (that do not carry any query or fragment parts) of those temporary files to xdg-open (see impl_showOfflineHelp in sfx2/source/appl/sfxhelp.cxx, and the discussion at <https://gerrit.libreoffice.org/#/c/47748/8/sfx2/source/appl/sfxhelp.cxx@702> "Call new help ").  The temporary HTML files contain http-equiv="refresh" and url="file:///...?..." with the original file URIs with query parts.
Now, these temporary files are created under /tmp in the LO flatpak, a filesystem tree that cannot be rewritten by the flatpak runtime's xdg-open to a pathname that is accessible from outside the flatpak (and can then be passed to an external browser), so xdg-open silently fails.  (It would be better if xdg-open failed with a non-zero exit code, which LO would communicate to the user.)
LO flatpak could be changed to instead create these temporary files under $XDG_CACHE_HOME (which is accessible form the outside).  But the temporary files' content still references absolute file URIs in the LO flatpak /app/libreoffice/instdir/program/../help/ tree, which would also need to be rewritten.
A second, minor, nuisance is that, for security reasons, an `xdg-open file:///...html` call from a flatpak leads to an intermediate popup dialog letting the user chose which application to use to open the URI, while e.g. an `xdg-open http:///...html` is allowed to go directly to the user's preferred browser.  So accessing help content from LO flatpak would present that popup dialog first, forcing the user to select a browser to proceed.

**Comment by Erick555** [comment]
> So accessing help content from LO flatpak would present that popup dialog first, forcing the user to select a browser to proceed.

Isn't this desired behavior for flatpak? It shouldn't spawn random apps without user consent.

**Comment by stbergmann** [comment]
> Isn't this desired behavior for flatpak? It shouldn't spawn random apps without user consent.
Yes.  But that doesn't mean that it's not a usability nuisance worth mentioning.  :)

**Comment by stbergmann** [comment]
A proposed solution (using a non-localized org.libreoffice.LibreOffice.Help extension that is not auto-downloaded by default) is upstream at <https://gerrit.libreoffice.org/#/c/65451/> "Enable --help=html for flatpak" now.

**Comment by stbergmann** [comment]
> However, per https://tools.ietf.org/html/rfc8089 "The 'file' URI Scheme", file URIs appear to not support a query (nor a fragment) part (I've written to the email address given at https://www.rfc-editor.org/info/rfc8089 seeking clarification of this).

see <https://mailarchive.ietf.org/arch/msg/art/VnL3SxwPwFtWWoATm7cab02HFu0> "[art] Question regarding RFC 8089"

**Comment by stbergmann** [comment]
> A proposed solution (using a non-localized org.libreoffice.LibreOffice.Help extension that is not auto-downloaded by default) is upstream at https://gerrit.libreoffice.org/#/c/65451/ "Enable --help=html for flatpak" now.

included in <https://flathub.org/builds/#/builders/2/builds/8017>

**Comment by LeandroStanger** [comment]
@ramcq org.libreoffice.LibreOffice.Help has to be downloaded automatically in Endless OS

**Comment by ramcq** [comment]
> @ramcq org.libreoffice.LibreOffice.Help has to be downloaded automatically in Endless OS

This is 1.3GB, I don't think we can spare that disk space on every image. Is that every language? We need to make this extension "locale-split" so that you can do language subsets.

**Comment by stbergmann** [comment]
> This is 1.3GB, I don't think we can spare that disk space on every image. Is that every language? We need to make this extension "locale-split" so that you can do language subsets.

As I wrote earlier: "A proposed solution (using a non-localized org.libreoffice.LibreOffice.Help extension that is not auto-downloaded by default) is upstream at https://gerrit.libreoffice.org/#/c/65451/ 'Enable --help=html for flatpak' now."  Follow that link for a rationale as to why that is not locale-split for now.
