### ISSUE TITLE
tweak app IDs from LibreOffice-foo to LibreOffice.foo

### ISSUE THREAD

**Issue by ramcq** [flathub/org.libreoffice.LibreOffice#36]
The code in Flatpak for exporting app data only understands LibreOffice.foo suffixes as "belonging" to the LibreOffice Flatpak - it considers LibreOffice-foo to belong to a different app named org.libreoffice.LibreOffice-foo. This is strictly correct - we should rename the .desktop files and app IDs we use in the solenv/assemble_flatpak.sh from org.libreoffice.LibreOffice-foo to org.libreoffice.LibreOffice.foo (and, if you are feeling kind, add an X-Endless-Alias to the .desktop file for the older ID).

**Comment by stbergmann** [comment]
* What negative consequences has the current setup (i.e., how to test that things will improve with a fix)?
* What "app IDs we use in the solenv/assemble_flatpak.sh" would be affected?  I only find "<id>org.libreoffice.LibreOffice.desktop</id>" in /app/share/appdata/org.libreoffice.LibreOffice.appdata.xml (if that's what you mean with app IDs), so no need for a change there.
* The .desktop files already contain other X-Endless-Alias entries via <https://github.com/flathub/org.libreoffice.LibreOffice/commit/715fbcfb4e5c51d40387998932984e54639476a1> "edit .desktop files to add X-Endless-Alias with original names".  What's the syntax to specify multiple such aliases?

**Comment by ramcq** [comment]
> * What negative consequences has the current setup (i.e., how to test that things will improve with a fix)?

Despite https://github.com/flathub/org.libreoffice.LibreOffice/blob/master/assemble-flatpak-desktop-integration.patch#L27-L32, only the org.libreoffice.LibreOffice appdata is visible in the exported flatpak repo. Ie, if you use `flatpak-builder --repo=repo` then `ostree --repo=repo cat appstream/x86_64 /appstream.xml.gz | zless` doesn't contain the appdata for the separate apps.

> * What "app IDs we use in the solenv/assemble_flatpak.sh" would be affected?  I only find "`<id>org.libreoffice.LibreOffice.desktop</id>`" in /app/share/appdata/org.libreoffice.LibreOffice.appdata.xml (if that's what you mean with app IDs), so no need for a change there.

The separate .desktop files are installed as org.libreoffice.LibreOffice-{writer,calc,...}.desktop and the appstream code I refer to above tries to match these IDs. Flatpak has a bug/inconsistency that it seems to allow such a .desktop file as a "sub ID", which it isn't strictly, but the appstream exporting is more pedantic and will only support an exact match, or a sub-ID with the . suffix. So the naming of the ID in the appstream and the naming of the desktop files should be consistent, and should use org.libreoffice.LibreOffice.{writer,calc,...}

> * The .desktop files already contain other X-Endless-Alias entries via <https://github.com/flathub/org.libreoffice.LibreOffice/commit/715fbcfb4e5c51d40387998932984e54639476a1> "edit .desktop files to add X-Endless-Alias with original names".  What's the syntax to specify multiple such aliases?

This is sadly actually broken on Endless at the moment, so we'll have to ignore it until we come up with a syntax that allows multiple entries. Updates from any published version of Endless (prior to today's 3.4.0 which switches to the Flatpak LibreOffice) will benefit most from the alias entries being libreoffice-foo.

**Comment by ramcq** [comment]
WIP at https://github.com/flathub/org.libreoffice.LibreOffice/tree/dotty-app-IDs but not tested successfully due to https://github.com/flatpak/flatpak/issues/1749

**Comment by stbergmann** [comment]
Seen fixed in <https://flathub.org/builds/#/builders/29/builds/1066>,
```
$ ls ~/.local/share/flatpak/exports/share/applications/org.libreoffice*
~/.local/share/flatpak/exports/share/applications/org.libreoffice.LibreOffice.base.desktop
~/.local/share/flatpak/exports/share/applications/org.libreoffice.LibreOffice.calc.desktop
~/.local/share/flatpak/exports/share/applications/org.libreoffice.LibreOffice.desktop
~/.local/share/flatpak/exports/share/applications/org.libreoffice.LibreOffice.draw.desktop
~/.local/share/flatpak/exports/share/applications/org.libreoffice.LibreOffice.impress.desktop
~/.local/share/flatpak/exports/share/applications/org.libreoffice.LibreOffice.math.desktop
~/.local/share/flatpak/exports/share/applications/org.libreoffice.LibreOffice.writer.desktop
~/.local/share/flatpak/exports/share/applications/org.libreoffice.LibreOffice.xsltfilter.desktop
```
