### ISSUE TITLE
LibreOffice crashes when getting input from ibus-libpinyin

### ISSUE THREAD

**Issue by Enaunimes** [flathub/org.libreoffice.LibreOffice#40]
I'm using ibus-libpinyin, which is the Chinese input method shipped in Fedora 28. LibreOffice Calc/Writer crashes whenever I try to type any Chinese in it.
LibreOffice from Fedora 28 repo works fine.

**Comment by stbergmann** [comment]
Looks like a missing backport of <https://cgit.freedesktop.org/libreoffice/core/commit/?h=libreoffice-6-0&id=f7d8a6ffae387a2698b07a8841e09ca3ed0bb000> "Resolves: tdf#116951 rhbz#1569331 start is G_MAXINT" to libreoffice-6-0-4.  Will do a build.

**Comment by Enaunimes** [comment]
Updated to the latest build and problem solved. Thanks a lot!
