### ISSUE TITLE
Again unable to open files on network shares

### ISSUE THREAD

**Issue by TiZ-EX1** [flathub/org.libreoffice.LibreOffice#41]
Hi there. This is a similar issue to #3. I can't re-open that and the fixes listed there don't work anymore. I'm using Xubuntu 18.04 and the distro's packaged flatpak 0.11.3. Attempting to open a file on a network share using my file manager gives an error dialog: "The operation on /run/user/1000/doc/d835cfa9/File Name.xlsx was started with an invalid parameter." If I try to open it inside of LO, I can't access network shares from the file picker.

Thanks for any help.

**Comment by stbergmann** [comment]
"Attempting to open a file on a network share using my file manager gives an error dialog [...]"
I don't understand what exactly you're doing in the flatpak'ed LO there?

**Comment by TiZ-EX1** [comment]
Double-clicking a file in a network share using Thunar, where LibreOffice is the default association.

**Comment by stbergmann** [comment]
While LO's "The operation on /run/user/1000/doc/d835cfa9/File Name.xlsx was started with an invalid parameter" dialog is still up, can you please do in a terminal `ps ux | grep -F soffice.bin` and capture the command line of that /app/libreoffice/program/soffice.bin process?

**Comment by TiZ-EX1** [comment]
Here you go: `/app/libreoffice/program/soffice.bin --calc /run/user/1000/doc/d835cfa9/19 - T2 Permit Ranges 18-19 - Copy.xlsx --splash-pipe=5`

**Comment by stbergmann** [comment]
And what kind of network share is that (i.e., what protocol)?  I cannot reproduce your issue, at least not with any protocols I've tried yet.

**Comment by TiZ-EX1** [comment]
It's samba. I'm going to hazard a guess that you've tried that one, it's the most common in enterprise environments.

**Comment by stbergmann** [comment]
Yes, cannot reproduce even with samba.  (Latest org.libreoffice.LibreOffice and org.freedesktop.Platform flatpaks, using GNOME's nautilus file manager, on Fedora 28.)
Only "unusual" part compared to opening a local document is LO presenting a "Document Could Not Be Locked [...] Open Read-Only [...]" dialog.

**Comment by stbergmann** [comment]
I assume this issue is caused by the accidental loss of GIO support when the LO flatpak was switched from the GNOME to the freedesktop.org runtime.  I'll provide fresh LO builds with GIO re-enabled.

**Comment by stbergmann** [comment]
@TiZ-EX1, please check whether <https://flathub.org/builds/#/builders/2/builds/2024> fixes the issue for you.

**Comment by TiZ-EX1** [comment]
Sorry it took a while to get back on this; I was on vacation. Can confirm the current build works for network shares.
