### ISSUE TITLE
Flatpak version missing Google Drive remote folder functionality

### ISSUE THREAD

**Issue by cgprats** [flathub/org.libreoffice.LibreOffice#49]
The "normal" version of libreoffice (the version downloadable from here:https://www.libreoffice.org/download/download/) has the option to save file to Google Drive. However the version from Flathub is missing this functionality.

See attached screenshots. (Top= deb version from libreoffice.org, bottom= version from Flathub)
![libreoffce_remote_deb](https://user-images.githubusercontent.com/11904594/43678960-bef40ba2-97ea-11e8-9da9-c0d665a60884.png)
![libreoffice_remote_flatpak](https://user-images.githubusercontent.com/11904594/43678961-bf0ddb40-97ea-11e8-8de2-ecde6b4ac383.png)

**Comment by stbergmann** [comment]
should be fixed with <https://flathub.org/builds/#/builders/2/builds/4244>
