### ISSUE TITLE
Langauge packs are missing

### ISSUE THREAD

**Issue by gyhun95** [flathub/org.libreoffice.LibreOffice#50]
Hy all, 
I've a serious problem with libre on endless os, or any other flatpak based system: I can't install hungarian UI langauge neither deb or rpm, and the modified gnome software doesn't include libreoffice-l10n-hu files... I'm helping to share libre here, but most people can't change to it, cause of lang problems.

Thanks for your help! Keep it up!

**Comment by stbergmann** [comment]
The LibreOffice Flatpak on Flathub has an org.libreoffice.LibreOffice.Locale extension that does include localization for various languages, including Hungarian.  However, depending on how you installed the LibreOffice Flatpak, the Locale extension may be missing or incomplete (containing only a subset of languages).  What works for me is an explicit `flatpak install --reinstall flathub org.libreoffice.LibreOffice.Locale`.  With that, `LC_ALL=hu_HU.UTF-8 flatpak run org.libreoffice.LibreOffice` brings up LibreOffice with Hungarian UI.
My understanding is that such missing/incomplete Locale extensions is not specific to the LibreOffice Flatpak, but is a general Flatpak issue, and you would need to ask for further advice in a forum suitable for your method of installing flatpaks (via command-line `flatpak` tool, via GNOME Software, etc.).

Flatpak is a distribution format that is different from and independent of the dep and rpm package formats.  I don't understand what you mean with "I can't install hungarian UI langauge neither deb or rpm" in this Flatpak context.

(But feel free to ask further questions here if you need more help.)
