### ISSUE TITLE
Build against org.freedesktop.Platform 18.08

### ISSUE THREAD

**Issue by juxi500** [flathub/org.libreoffice.LibreOffice#54]
Hello,

since org.freedesktop.Platform 18.08 was released, would it be possible to build LibreOffice flatpak against it (instead of org.freedesktop.Platform 1.6)?

Thank you very much and have a nice day :)

**Comment by stbergmann** [comment]
As discussed on freenode #flatpak the other day:
> Aug 15 13:27:13 <sberg>	ramcq, btw, what's your thoughts on rebasing LO on the new freedesktop 18.08 runtime? asking as you wanted to consolidate multiple apps on a single runtime in the past (so LO dropped the GNOME runtime)
> Aug 15 13:30:44 <ramcq>	if you could wait a bit until GNOME 3.30 comes out with the FD 18.08 as base, so that we get more apps moving at once, that would be good
> Aug 15 13:31:13 <ramcq>	but also, it's kind of inevitable for us, so I won't expect you just to follow our requirements
> Aug 15 13:39:26 <sberg>	ramcq, that's fine; I'm not planning to rebase immediately anyway, just thought might be worth asking you :)

So maybe do that for the next major LO 6.2.

**Comment by akurtakov** [comment]
Is there any movement here?

**Comment by stbergmann** [comment]
This is still planned for LO 6.2.  Do you ask for a specific reason?

**Comment by jjardon** [comment]
I think this can be closed now?
