### ISSUE TITLE
Extension may need to access to DBUS

### ISSUE THREAD

**Issue by julroy67** [flathub/org.libreoffice.LibreOffice#59]
Flatpak version of LibreOffice crashes when installing the grammar spellcheck extension named Antidote.

I already reported the bug as [FDO#121242](https://bugs.documentfoundation.org/show_bug.cgi?id=121242), but it maybe flatpak bug.

It throws this error about dbus : 
`Erreur à l'enregistrement du service : org.freedesktop.DBus.Error.ServiceUnknown`

When adding the --socket=session-bus to the command line, LibreOffice doesn't crash anymore but the extension still doesn't work.

**Comment by stbergmann** [comment]
<https://bugs.documentfoundation.org/show_bug.cgi?id=121242#c3>: "Unfortunately, I don't think it is possible to download it for free."
In which case you'll need to approach the provider of that closed Antidote extension for support.
(I'm closing this issue again, but we can keep <https://bugs.documentfoundation.org/show_bug.cgi?id=121242> "Libreoffice (flatpak) segfaults after extension installation" open if you like; it contains a superset of the information provided here, anyway. But I'm not sure we can do anything useful with that issue as long as we have no source code for the problematic extension.)
