### ISSUE TITLE
Flatpak LibreOffice 6.1.* vcl stuck with GTK on KDE Plasma and won't work with Global Menu

### ISSUE THREAD

**Issue by aldevel** [flathub/org.libreoffice.LibreOffice#63]
System and installed Flatpak LibreOffice:
KDE neon 5.14
KDE Plasma version: 5.14.4
KDE Frameworks Version: 5.52.0
Qt Version: 5.11.2
Kernel Version: 4.15.0-42-generic
OS Type: 64-bit
Flatpak version: 1.0.1
___
Version: 6.1.3.2
Build ID: 86daf60bf00efa86ad547e59e09d6bb77c699acb
CPU threads: 8; OS: Linux 4.15; UI render: default; VCL: gtk3; 
Flatpak
Locale: en-US (en_US.UTF-8); Calc: group threaded
___
___
Unfortunately only the current beta release LibreOffice works with KDE GlobalMenu so based on this fact and if Flatpak LibreOffice have to stick with stable release only then this report have to be neglected.
However even in the case above, I still have one question, will 6.2.* Flatpak LibreOffice version's vcl use KDE5 on KDE Plasma environment or will it stick with GTK too?

Related bug report:
https://bugs.documentfoundation.org/show_bug.cgi?id=113397
___
Working version with appimage package on system above:
Version: 6.2.0.0.beta1
Build ID: d1b41307be3f8c19fe6f1938cf056e7ff1eb1d18
CPU threads: 8; OS: Linux 4.15; UI render: default; VCL: kde5; 
Locale: en-US (en_US.UTF-8); UI-Language: en-US
Calc: CL

Thank you!

**Comment by aldevel** [comment]
What do you mean, against Gnome environment? I experience absolutely the opposite. I think you missed my point, at least there is not a single thing against Gnome by LO's GTK vcl. It's not about how LibreOffice integrate its GTK elements into KDE but how incapable it is to use elements from KDE and being used by KDE. I don't arguing here, I'm not even capable for that :) and there is nothing to discuss I think. My question is fundamentally wrong anyways because it's obvious the 6.2 version's vlc will use the new kde5 integration in Flatpak too except if someone rewrite the related stuff entirely.
Is it few patches to implement a software into Flatpak? Interesting. When 6.2 becomes stable it'll be implemented into Flatpak sooner or later anyway. Until then I use other sources and basically I wanted to ask when should I check on Flatpak LO.

**Comment by stbergmann** [comment]
"What do you mean, against Gnome environment?": The org.freedesktop.Platform//1.6 that the LO flatpak uses is kind of GNOME-oriented.  It e.g. provides /lib/libgtk-3.so and other GNOME-related libraries, but no KDE-related libraries.  The LO flatpak only contains the gtk3 VCL plugin (/app/libreoffice/program/libvclplug_gtk3lo.so), and---as far as is planned---will continue to only contain that VCL plugin in LO 6.2 etc.
Desktop integration of the LO flatpak is thus "smoother" (by whatever definition of smoothness) on a GNOME desktop than on a KDE desktop; and on a KDE desktop, integration of the native LO is smoother than that of LO flatpak.
That being said, there may be certain features of certain desktops that currently do not work with LO flatpak but that could be made to work with relatively little effort (by somebody who's versed in those specific desktops' features and/or in the details of the org.freedesktop.Platform flatpak runtime).  "KDE GlobalMenu" (and I have no idea what that even is) may or may not be such a case.  I'm fine with leaving this issue open in case somebody who knows the details comes along and might fix it.

**Comment by aldevel** [comment]
Thank you for the clarification. I think you know what Global Application Menu is, maybe you'd call it something else. It's simple a function in given desktop environment what shows given application menus on given dock/panel instead of application window and it was a real issue before and now it works on my system with 6.2 LO version, the bug report I posted above explains it too. I have to note that's the issue I consider least, there're lot other things what works much more flawlessly with kde5 VCL. Anyhow I'll check on LO Flatpak continuously because it'd be the most convenient source to get LO, at least for me on my system currently.

**Comment by Alexander-Wilms** [comment]
I tried building LibreOffice with GTK3 and Qt VCL plugins by using KDE SDK 5.12 as well as `--enable-qt5` and got this error:

```
[CXX] vcl/qt5/Qt5AccessibleEventListener.cxx
[CXX] vcl/qt5/Qt5AccessibleWidget.cxx
[CXX] vcl/qt5/Qt5Bitmap.cxx
In file included from /usr/include/c++/8.2.0/bits/stl_algo.h:59,
                 from /usr/include/c++/8.2.0/algorithm:62,
                 from /usr/include/QtCore/qglobal.h:142,
                 from /usr/include/QtCore/qnamespace.h:43,
                 from /usr/include/QtCore/qobjectdefs.h:48,
                 from /usr/include/QtCore/qobject.h:46,
                 from /usr/include/QtCore/QObject:1,
                 from /run/build/libreoffice/vcl/inc/qt5/Qt5AccessibleWidget.hxx:14,
                 from /run/build/libreoffice/vcl/qt5/Qt5AccessibleWidget.cxx:20:
/usr/include/c++/8.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
make[1]: *** [/run/build/libreoffice/solenv/gbuild/LinkTarget.mk:293: /run/build/libreoffice/workdir/CxxObject/vcl/qt5/Qt5AccessibleWidget.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/c++/8.2.0/ext/string_conversions.h:41,
                 from /usr/include/c++/8.2.0/bits/basic_string.h:6391,
                 from /usr/include/c++/8.2.0/string:52,
                 from /usr/include/c++/8.2.0/bits/locale_classes.h:40,
                 from /usr/include/c++/8.2.0/bits/ios_base.h:41,
                 from /usr/include/c++/8.2.0/ios:42,
                 from /usr/include/c++/8.2.0/ostream:38,
                 from /run/build/libreoffice/include/rtl/ustring.hxx:28,
                 from /run/build/libreoffice/include/com/sun/star/uno/Any.h:26,
                 from /run/build/libreoffice/workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/uno/XInterface.hdl:6,
                 from /run/build/libreoffice/workdir/UnoApiHeadersTarget/offapi/normal/com/sun/star/accessibility/XAccessible.hdl:7,
                 from /run/build/libreoffice/workdir/UnoApiHeadersTarget/offapi/normal/com/sun/star/accessibility/XAccessible.hpp:6,
                 from /run/build/libreoffice/vcl/inc/qt5/Qt5AccessibleEventListener.hxx:12,
                 from /run/build/libreoffice/vcl/qt5/Qt5AccessibleEventListener.cxx:20:
/usr/include/c++/8.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
make[1]: *** [/run/build/libreoffice/solenv/gbuild/LinkTarget.mk:293: /run/build/libreoffice/workdir/CxxObject/vcl/qt5/Qt5AccessibleEventListener.o] Error 1
make: *** [Makefile:286: build] Error 2
```

I'm not sure if I should file a bug report against the KDE SDK or LibreOffice, though

**Comment by stbergmann** [comment]
please keep this issue focussed

**Comment by stbergmann** [comment]
@aldevel With a build of LibreOffice 7.2.5.2 including <https://github.com/flathub/org.libreoffice.LibreOffice/pull/174> "Add global-menu support for KDE and unity" available now on Flathub, you may want to check whether that fixes this issue for you.

**Comment by Erick555** [comment]
Note that LO flatpak still has only GTK vcl which is part of reported issue.

**Comment by rom1dep** [comment]
Shimming in to confirm the problem still present in 7.5, and that https://github.com/flathub/org.libreoffice.LibreOffice/pull/174 didn't improve things.

Here are some observations/thoughts:
- Qt apps (flatpak and not) behave well (they successfully expose their menu)
- My distro's native libreoffice package (which uses the kde VCL backend) does as well
- GTK apps do not (but they tend to retain their menu in the main window, which **libreoffice doesn't**)
- Poking further at GTK, it seems to be a wayland-specific issue: https://bugs.kde.org/show_bug.cgi?id=424485

So it seems to me that either of those could improve the situation:
- this flatpak could ship the kde VCL backend (and I would expect things to work as well as with the distro's packages)
- LO could force its menu to be shown in-app when run from wayland

**Comment by AlphaCraft9658** [comment]
Hi! Any updates on this? As it's already more than one year later and this still is an issue. My distro has dropped the native package and if I want updates, I'm kinda forced to use the flatpak. That's not an issue, but the lack of qt-style support makes it look out of place and is pretty annoying.

**Comment by stbergmann** [comment]
> @aldevel With a build of LibreOffice 7.2.5.2 including #174 "Add global-menu support for KDE and unity" available now on Flathub, you may want to check whether that fixes this issue for you.

...with the "won't work with Global Menu" part of the original issue thus out of the way,...

> Note that LO flatpak still has only GTK vcl which is part of reported issue.

...lets subsume the remainder of this issue under <https://github.com/flathub/org.libreoffice.LibreOffice/issues/270> "Move to the KDE runtime"
