### ISSUE TITLE
Zotero plugin does not work

### ISSUE THREAD

**Issue by mczimmermann** [flathub/org.libreoffice.LibreOffice#7]
Having Zotero 5.0.33 installed I can use it in a non-flatpak'd LibreOffice installation but not in the flatpak'd version. Considering that Zotero flathub/flathub#221 is currently under review for being on Flathub, I think it would be great if these two would work well together. (Same is also true for Mendeley flathub/flathub#192)

**Comment by mczimmermann** [comment]
Tested it again with LibreOffice 6.0 and it just works now thanks to the Java Runtime Environment! 

Many thanks for the great work!

![screenshot from 2018-02-02 14-33-02](https://user-images.githubusercontent.com/34868497/35735883-77c869e8-0826-11e8-972d-c02446e81731.png)

**Comment by mczimmermann** [comment]
I had to install it manually from the Zotero_OpenOffice_Integration.oxt because Zotero did not detect the flatpak'd LibreOffice installation.

I am not sure whether this is a Zotero or LibreOffice problem, but it would be nice if a flatpak'd Zotero would automatically detect a flatpak'd LibreOffice to install the plugin.  Where should I open an issue?

**Comment by nedrichards** [comment]
This is kind of the point of running apps in contained sandboxes, that they don't leak evidence of their existence to each other. For inter-app comms questions you should probably look at the portals or main flatpak repos. All in this org: https://github.com/flatpak/

**Comment by stbergmann** [comment]
One channel through which flatpak'ed and non-flatpak'ed apps (and also one flatpak'ed app to a different flatpak'ed app) can interact is xdg-open.  For example, from outside of flatpak, `xdg-open /path/to/some.oxt` will start the LO flatpak to register the some.oxt LO extension (similar to how `xdg-open /path/to/some.odt` will start the LO flatpak to display the some.odt text document).  For another example, the LO flatpak uses executes `xdg-open https://help.libreoffice.org/...` to display its online help content in some browser (running outside the LO flatpak).

But I fear that Zotero would want to communicate with LO in a more intimate way (presumably using LO's UNO mechanisms), and that is indeed not supported by a flatpak'ed LO.

**Comment by mczimmermann** [comment]
To clarify, once installed the Zotero plugin works as intended. I am only talking about the plugin installation, which is not as simple as for the non flatpakd versions. I think making the .oxt file available to LO in some way should be sufficient. Then this is an upstream issue for Zotero?

**Comment by koenigjaeger** [comment]
@mczimmermann  or anyone what method was used to get it working? I couldn't find Zotero_OpenOffice_Integration.oxt. Did it have to be downloaded and then it detected the flatpaked zotero install from the flatpaked libreoffice install?

**Comment by koenigjaeger** [comment]
Update for other users (All in Flatpak):

1. To install manually go to Zotero's preferences `Edit/Preferences/Cite/Word Processors` 
2. Then select the option to manually install the add-on. 
3. Open the add-on with libreoffice.
4. Restart and open libreoffice and you are all set!

Useful Links: https://forums.zotero.org/discussion/comment/325212#Comment_325212
