### ISSUE TITLE
Comments in Calc don't showup on mouse hover

### ISSUE THREAD

**Issue by janxkoci** [flathub/org.libreoffice.LibreOffice#79]
I downloaded some excel spreadsheet from NCBI to fill in my samples' data and I noticed the comments in the spreadsheet didn't show up on mouse hover. I could right-click the cell and make it show up from there, but that's permanent and not what I want.

Opening the same file using LO 6.1 from Ubuntu PPA worked properly, same for OnlyOffice appimage. The comments in both cases worked as expected.

The issue is present at least in Ubuntu 18.04 LTS and elementary OS 5.0.

**Comment by stbergmann** [comment]
That is most likely upstream <https://bugs.documentfoundation.org/show_bug.cgi?id=120797> "Comment not displayed on hovering" (affecting LO 6.2 with the GTK3 VCL backend, which is the VCL backend that the flatpak build uses unconditionally).

**Comment by janxkoci** [comment]
I see. Sorry I didn't think such regression was in LO as their job in the 6.x series is just amazing. My bad.
