### ISSUE TITLE
bwrap: Can't mkdir parents for /run/host/usr: Permission denied

### ISSUE THREAD

**Issue by trialism** [flathub/org.libreoffice.LibreOffice#8]
When I start libreoffice as `flatpak run org.libreoffice.LibreOffice` it throws the error to me what's in the title.

**Comment by stbergmann** [comment]
So this doesn't appear to be an issue with the LO flatpak, but rather with flatpak and/or bwrap itself.  Closed as duplicate of <https://github.com/flatpak/flatpak/issues/1357>.
