### ISSUE TITLE
LibreOffice cannot be launched with flatpak in normal mode on ASUS E402YA

### ISSUE THREAD

**Issue by starnight** [flathub/org.libreoffice.LibreOffice#82]
When I opened LibreOffice (6.2.2.2 release got from Flathub) with the flatpak, it always fails after the LibreOffice's banner and then no response.
I got the stace by executing `flatpak run --devel org.libreoffice.LibreOffice --strace`
[strace.log](https://github.com/flathub/org.libreoffice.LibreOffice/files/3088014/strace.log)

By the way, if I launch it in safe mode: `flatpak run org.libreoffice.LibreOffice --safe-mode`, LibreOffice can be opened.

Compare to other computers.  This issue only happens on ASUS E402YA equipped with AMD E2-7015 APU with AMD Radeon R2 Graphics that we have.

**Comment by starnight** [comment]
After remove `~/.var/app/org.libreoffice.LibreOffice/config/libreoffice`, LibreOffice still cannot start without `--safe-mode`.

**Comment by starnight** [comment]
I found if I start LibreOffice in safe mode.  Config in the popped up "Safe Mode" dialog and choose Configure -> "Disable hardware acceleration", then press "Apply Changes and Restart".  It can be start without `--safe-mode`.

Comparing to previous state, I notice it has become "OpenCL is not used" in OpenCL.
![Screenshot from 2019-04-17 16-07-30](https://user-images.githubusercontent.com/2100946/56273959-69088000-6130-11e9-9434-9e255601cd4f.png)
Graphics Output is still the same as "Use hardware acceleration" in View.
![Screenshot from 2019-04-17 16-07-25](https://user-images.githubusercontent.com/2100946/56274205-ed5b0300-6130-11e9-8b1a-879ac30d0d32.png)

**Comment by stbergmann** [comment]
So my bet would be a failure during Desktop::CheckOpenCLCompute (desktop/source/app/opencl.cxx).  Please check whether `flatpak run --env=SAL_DISABLE_OPENCL=1 org.libreoffice.LibreOffice` makes the issue go away for you.
(And btw, when you originally wrote "it always fails after the LibreOffice's banner and then no response" you mean that start splash banner disappears and the `flatpak run ...` exits and no other kind of output happens, or something else?)

**Comment by stbergmann** [comment]
Midair collision :)  So your latest comments already confirm my bet.

**Comment by starnight** [comment]
> So my bet would be a failure during Desktop::CheckOpenCLCompute (desktop/source/app/opencl.cxx). Please check whether `flatpak run --env=SAL_DISABLE_OPENCL=1 org.libreoffice.LibreOffice` makes the issue go away for you.

Double confirmed `flatpak run --env=SAL_DISABLE_OPENCL=1 org.libreoffice.LibreOffice` works.

> (And btw, when you originally wrote "it always fails after the LibreOffice's banner and then no response" you mean that start splash banner disappears and the `flatpak run ...` exits and no other kind of output happens, or something else?)

Start splash banner disappears,  `flatpak run ...` does not exit and no other kind of output happens.

**Comment by stbergmann** [comment]
> > So my bet would be a failure during Desktop::CheckOpenCLCompute (desktop/source/app/opencl.cxx). Please check whether `flatpak run --env=SAL_DISABLE_OPENCL=1 org.libreoffice.LibreOffice` makes the issue go away for you.
> 
> Double confirmed `flatpak run --env=SAL_DISABLE_OPENCL=1 org.libreoffice.LibreOffice` works.

I guess I'll set the default for "Allow use of OpenCL" to false for the LO Flatpak build, then.

> > (And btw, when you originally wrote "it always fails after the LibreOffice's banner and then no response" you mean that start splash banner disappears and the `flatpak run ...` exits and no other kind of output happens, or something else?)
> 
> Start splash banner disappears, `flatpak run ...` does not exit and no other kind of output happens.

So it doesn't crash but hangs?  That's interesting.  If you find the time for the following experiment, that data could be useful:  With `org.libreoffice.LibreOffice.Debug` extension installed, run `flatpak run --devel --command=bash org.libreoffice.LibreOffice`, then inside the Flatpak shell run `gdb /app/libreoffice/program/soffice.bin`, then in the debugger type `run`.  Once LO is past the splash screen and is hanging, type Ctrl+C in the debugger, type `thread all apply backtrace` and provide its output.  (Then `kill` and `quit` to exit the debugger, and `exit` to exit the Flatpak shell.)

**Comment by stbergmann** [comment]
@starnight: And what Linux distro version do you use?

**Comment by starnight** [comment]
I got the gdb log.
[gdbtrace.log](https://github.com/flathub/org.libreoffice.LibreOffice/files/3093245/gdbtrace.log)

I use Endless OS 3.5-nexthw1 and hit this issue originally.  To debug the problem, I installed Fedora 29 and debug on it now.

**Comment by starnight** [comment]
> > > So my bet would be a failure during Desktop::CheckOpenCLCompute (desktop/source/app/opencl.cxx). Please check whether `flatpak run --env=SAL_DISABLE_OPENCL=1 org.libreoffice.LibreOffice` makes the issue go away for you.
> > 
> > 
> > Double confirmed `flatpak run --env=SAL_DISABLE_OPENCL=1 org.libreoffice.LibreOffice` works.
> 
> I guess I'll set the default for "Allow use of OpenCL" to false for the LO Flatpak build, then.

I can test again if there is a new version for the fix.  We have the broken and none broken laptops.

**Comment by stbergmann** [comment]
> I guess I'll set the default for "Allow use of OpenCL" to false for the LO Flatpak build, then.

That should be working now in the latest LO 6.2.3 build, <https://flathub.org/builds/#/builders/32/builds/2557>.

> I got the gdb log.
> [gdbtrace.log](https://github.com/flathub/org.libreoffice.LibreOffice/files/3093245/gdbtrace.log)
> 
> I use Endless OS 3.5-nexthw1 and hit this issue originally. To debug the problem, I installed Fedora 29 and debug on it now.

The log unfortunately doesn't give much of a clue why it hangs.  There might be a deadlock between thread 1 and thread 12 (maybe even after a crash in the latter, as it has a llvm::PrettyStackTraceEntry::PrettyStackTraceEntry frame, which might have to do with printing of a backtrace after a crash), but hard to tell, and only involving 3rd party system code anyway.  So I'll close this for now.  Feel free to reopen when there's further insight into what exactly goes wrong.
