### ISSUE TITLE
ssh problem

### ISSUE THREAD

**Issue by sandrolemosmachado** [flathub/org.libreoffice.LibreOffice#83]
I can not get dislplay permission when running libreoffice over ssh. I use LTSP thin client machines so this feature is crucial to me. Running locally is ok

**Comment by stbergmann** [comment]
@sandrolemosmachado, is this specific to LibreOffice?
@alexlarsson, any idea what this could be?

**Comment by sandrolemosmachado** [comment]
I managed to solve this using the following command:

flatpak run --branch=stable --arch=x86_64
--command=/app/libreoffice/program/soffice --share=network
--filesystem=host --file-forwarding org.libreoffice.LibreOffice --calc
--display $DISPLAY

Thanks


Sandro Lemos Machado
Professor Associado da Universidade Federal da Bahia
Coordenador PGENAM
Coordenador do Laboratório de Geotecnia Ambiental
CV: http://lattes.cnpq.br/2272781877323360
TELs: +5571 3283-9845/9461/9846
         +5571 9989-1724


Em ter, 23 de abr de 2019 às 05:14, stbergmann <notifications@github.com>
escreveu:

**Comment by stbergmann** [comment]
...so lets close
