### ISSUE TITLE
Making LibreOffice recognize other language dictionaries apart from English

### ISSUE THREAD

**Issue by avinash** [flathub/org.libreoffice.LibreOffice#84]
Hi,

I'm running the latest LibreOffice (6.2.3.2) using Flatpak under Fedora Linux 29 and it's working great.

I regularly write documents in both English and French and I can't get LibreOffice to recognize the French dictionary which I already have on my system, thanks to Hunspell:

hunspell-fr-6.2-2.fc29.noarch

The English dictionary is working well. I have noticed that in Tools > Options > Language Settings > Languages, only the different variants of English have a tick next to them. Even though, I have hunspell-fr, there is no green tick next to French.

Furthermore, in Tools > Options > Language Settings > Writing Aids, it is clear that the hunspell-fr is not being recognized by LibreOffice. 

Here is what I get when I do a flatpak list --all:

```
Scribus - Open Source Page Layout and Desktop Publishing (DTP)	net.scribus.Scribus		stable	x86_64	flathub	system
Freedesktop.org Application Platform version 18.08 - Shared libraries provided by freedesktop.org	org.freedesktop.Platform		18.08	x86_64	flathub	system
Locale	org.freedesktop.Platform.Locale		18.08	x86_64	flathub	system
html5-codecs	org.freedesktop.Platform.html5-codecs		18.08	x86_64	flathub	system
GNU Image Manipulation Program - Create images and edit photographs	org.gimp.GIMP	2.10.10	stable	x86_64	flathub	system
GNOME Application Platform version 3.30 - Shared libraries used by GNOME applications	org.gnome.Platform		3.30	x86_64	flathub	system
Locale	org.gnome.Platform.Locale		3.30	x86_64	flathub	system
Inkscape - Vector Graphics Editor	org.inkscape.Inkscape	0.92.4	stable	x86_64	flathub	system
Locale	org.inkscape.Inkscape.Locale		stable	x86_64	flathub	system
Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme	org.kde.KStyle.Adwaita		5.12	x86_64	flathub	system
KDE Application Platform - Shared libraries used by KDE applications	org.kde.Platform		5.12	x86_64	flathub	system
Locale	org.kde.Platform.Locale		5.12	x86_64	flathub	system
QGnomePlatform - Qt Platform Theme aimed to accommodate GNOME settings	org.kde.PlatformTheme.QGnomePlatform		5.12	x86_64	flathub	system
Sources	org.kde.PlatformTheme.QGnomePlatform.Sources		5.12	x86_64	flathub	system
LibreOffice - The LibreOffice productivity suite	org.libreoffice.LibreOffice	6.2.3.2	stable	x86_64	flathub	system
Locale	org.libreoffice.LibreOffice.Locale		stable	x86_64	flathub	system
VLC - VLC media player, the open-source multimedia player	org.videolan.VLC		stable	x86_64	flathub	system
Locale	org.videolan.VLC.Locale		stable	x86_64	flathub	system
```

I have tried to install the Freedesktop.org Application Platform 1.6 as per a previous comment in another issue but it does not fix the issue.

Any idea of what is wrong? Thanks.

**Comment by stbergmann** [comment]
LO is by now based on org.freedesktop.Platform//18.08 (you can find that out with `flatpak info org.libreoffice.LibreOffice`), so what should help is `flatpak install --reinstall flathub org.freedesktop.Platform.Locale//18.08`.

**Comment by avinash** [comment]
Fantastic.

Running `flatpak install --reinstall flathub org.freedesktop.Platform.Locale//18.08` cured the issue. Now, in addition to English, I have French + a lot of languages which I don't need but which I heartily welcome :-)

Can you please clarify something for me. When I did `flatpak list --all` previously, I did have the following line:

`Locale	org.freedesktop.Platform.Locale		18.08	x86_64	flathub	system`

which I guess was incomplete (I don't really understand why...) Doing the reinstall downloaded quite a lot of new things (about 100Mb of them) and this is why I guess the dictionaries work now. My question is: do we need to "reinstall" flatpaks regularly and does this need to be done manually?

Thanks.

**Comment by stbergmann** [comment]
The *.Locale extensions are special, in that flatpak by default only downloads that part of such an extension that matches the users current system locale, while the --reinstall hack unconditionally downloads all of it.  There obviously needs to be usability improvements here, as this appears to be a common issue for users.

**Comment by avinash** [comment]
Thanks. This is definitely a major issue for all those who need to write documents in languages other than English (assuming the UI is in English of course).

**Comment by danilo-alm** [comment]
To install only the languages you need, eg. for english and portuguese:
`flatpak config languages --set "en;de;fr"`
then:
`flatpak update`

[Source](https://www.ctrl.blog/entry/flatpak-locale-dictionaries.html)
