### ISSUE TITLE
“Preview in Web Browser” does not work in Flatpak version

### ISSUE THREAD

**Issue by ovari** [flathub/org.libreoffice.LibreOffice#85]
Description:
Menu Bar → File → “Preview in Web Browser” does not work in Flatpak version

Steps to Reproduce:
1. On Linux, install LibreOffice from Flathub https://flathub.org/
2. Open the Flatpak version of LibreOffice
3. Select the “File” menu
4. Select “Preview in Web Browser”

Actual Results:
Nothing happens

Expected Results:
Open in the default web broswer

Reproducible: Always

User Profile Reset: No

Additional Info:
Linux Mint 19.1 Cinnamon
https://bugs.documentfoundation.org/show_bug.cgi?id=124998

Thank you

**Comment by ovari** [comment]
Thank you

**Comment by stbergmann** [comment]
fix available in <https://flathub.org/builds/#/builders/32/builds/3048>

**Comment by ovari** [comment]
Is this the same as https://flathub.org/apps/details/org.libreoffice.LibreOffice updated May 3, 2019?
Thank you

**Comment by stbergmann** [comment]
> Is this the same as https://flathub.org/apps/details/org.libreoffice.LibreOffice updated May 3, 2019?

Yes, it's the latest org.libreoffice.LibreOffice build available on flathub.
