### ISSUE TITLE
Font rendering is ugly on Wayland KDE/Plasma desktop

### ISSUE THREAD

**Issue by rbrooklyn** [flathub/org.libreoffice.LibreOffice#89]
System information:
KDE 5.15
Monitor: 1 1440p screen. No scaling settings changes so should be 100%
OS: Arch Linux, 5.1 Kernel.

When running on Wayland, Libreoffice is very ugly with it's font rendering, making it a bit of a chore to use. See the below screenshot (Native application on the left, Flatpak on the right) :
[https://i.imgur.com/hOT51xR.png](https://i.imgur.com/hOT51xR.png)

When running on Xorg, the font rendering is acceptable for both native and flatpak:
[https://i.imgur.com/hOT51xR.png](https://i.imgur.com/ZoFJ6xm.png)

Hexchat, another GTK application which I've installed through flathub, runs perfectly well under both Wayland and X with no font rendering issues, so I'm unsure where to point the blame.

It would appear that maybe Libreoffice is getting confused about how to scale it's font's somehow under Wayland, but this isn't an issue under X, which would suggest maybe that something about the Wayland setup isn't passing some required information accurately. My experience in this area is very limited.

**Comment by stbergmann** [comment]
Is that the latest LO 6.2.4 flatpak (see "Help - About LibreOffice"; you can copy/paste the leading lines with all the details there)?

**Comment by rbrooklyn** [comment]
On xorg:
Version: 6.2.4.2
Build ID: 2412653d852ce75f65fbfa83fb7e7b669a126d64
CPU threads: 4; OS: Linux 5.1; UI render: default; VCL: gtk3; 
Flatpak
Locale: en-GB (en_GB.UTF-8); UI-Language: en-GB
Calc: threaded

**Comment by stbergmann** [comment]
I prepared a LO 6.2.4.2 flatpak build with a patch (see below) producing some log output on stderr, in case some suspect part of the code would indeed misbehave.  The flatpak bundle is available for download at http://people.redhat.com/sbergman/LO-debug.bundle (to be installed with `flatpak install --bundle LO-debug.bundle` and run with `flatpak run org.libreoffice.LibreOffice//test`).

I tried it on a laptop (with built-in hidpi display), with Plasma on Fedora 30 under both X11 and Wayland, and in both cases the fonts looked crisp to me and the debug logs didn't show anything suspicious.  (I noticed, though, that Plasma on Wayland would automatically adapt to the hidpi display, apparently doing some scaling behind the scenes, while everything looked tiny with Plasma on X11.)

Just to be sure, you could run that test build too and provide its stdout/stderr output.

(For reference, the patch I used is
```
diff --git a/vcl/inc/salinst.hxx b/vcl/inc/salinst.hxx
index 4acb0315de4c..20c5e9cce268 100644
--- a/vcl/inc/salinst.hxx
+++ b/vcl/inc/salinst.hxx
@@ -1,3 +1,4 @@
+#include<sal/log.hxx>
 /* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
 /*
  * This file is part of the LibreOffice project.
@@ -207,7 +208,7 @@ public:
     /// get information about underlying versions
     virtual OUString        getOSVersion() { return OUString("-"); }
 
-    virtual const cairo_font_options_t* GetCairoFontOptions() { return nullptr; }
+    virtual const cairo_font_options_t* GetCairoFontOptions() { SAL_DEBUG("DEBUG.1");return nullptr; }
 };
 
 // called from SVMain
diff --git a/vcl/unx/gtk/gtkinst.cxx b/vcl/unx/gtk/gtkinst.cxx
index f18dc9457fd5..0db21d9672d2 100644
--- a/vcl/unx/gtk/gtkinst.cxx
+++ b/vcl/unx/gtk/gtkinst.cxx
@@ -466,6 +466,7 @@ GtkInstance::getPrintWrapper() const
 const cairo_font_options_t* GtkInstance::GetCairoFontOptions()
 {
     const cairo_font_options_t* pCairoFontOptions = gdk_screen_get_font_options(gdk_screen_get_default());
+    SAL_DEBUG("DEBUG.2 "<<pCairoFontOptions);
     if (!m_pLastCairoFontOptions && pCairoFontOptions)
         m_pLastCairoFontOptions = cairo_font_options_copy(pCairoFontOptions);
     return pCairoFontOptions;
diff --git a/vcl/unx/gtk/gtksalframe.cxx b/vcl/unx/gtk/gtksalframe.cxx
index 3316bc0705e6..24f087204304 100644
--- a/vcl/unx/gtk/gtksalframe.cxx
+++ b/vcl/unx/gtk/gtksalframe.cxx
@@ -2952,6 +2952,7 @@ void GtkSalFrame::signalStyleSet( GtkWidget*, GtkStyle* pPrevious, gpointer fram
             bFontSettingsChanged = !cairo_font_options_equal(pLastCairoFontOptions, pCurrentCairoFontOptions);
         else if (!pLastCairoFontOptions && !pCurrentCairoFontOptions)
             bFontSettingsChanged = false;
+        SAL_DEBUG("DEBUG.3 "<<pLastCairoFontOptions<<" "<<pCurrentCairoFontOptions<<" "<<int(bFontSettingsChanged));
         if (bFontSettingsChanged)
         {
             pInstance->ResetLastSeenCairoFontOptions(pCurrentCairoFontOptions);
diff --git a/vcl/unx/gtk3/gtk3gtkframe.cxx b/vcl/unx/gtk3/gtk3gtkframe.cxx
index 27d186923b6f..412c7b4d4645 100644
--- a/vcl/unx/gtk3/gtk3gtkframe.cxx
+++ b/vcl/unx/gtk3/gtk3gtkframe.cxx
@@ -3189,6 +3189,7 @@ void GtkSalFrame::signalStyleUpdated(GtkWidget*, gpointer frame)
         bFontSettingsChanged = !cairo_font_options_equal(pLastCairoFontOptions, pCurrentCairoFontOptions);
     else if (!pLastCairoFontOptions && !pCurrentCairoFontOptions)
         bFontSettingsChanged = false;
+    SAL_DEBUG("DEBUG.4 "<<pLastCairoFontOptions<<" "<<pCurrentCairoFontOptions<<" "<<int(bFontSettingsChanged));
     if (bFontSettingsChanged)
     {
         pInstance->ResetLastSeenCairoFontOptions(pCurrentCairoFontOptions)
```
)

**Comment by rbrooklyn** [comment]
Hello,

Thanks for your efforts.

I have attached the log produced by the bundle you sent. I launched the flatpak, opened a new Writer document and then closed the file without saving. Attached is a copy and paste from the terminal output.

For what it's worth, my mouse pointer is larger in Wayland than Xorg, despite only changing the session in SDDM and not changing settings elsewhere. This seems minor but might be a indicator to a bigger issue.

[wayland.log](https://github.com/flathub/org.libreoffice.LibreOffice/files/3228739/wayland.log)

**Comment by stbergmann** [comment]
> I have attached the log produced by the bundle you sent. I launched the flatpak, opened a new Writer document and then closed the file without saving. Attached is a copy and paste from the terminal output.

Thanks.  But unfortunately the output looks fine, so the problem is probably somewhere else after all.
 
> For what it's worth, my mouse pointer is larger in Wayland than Xorg, despite only changing the session in SDDM and not changing settings elsewhere. This seems minor but might be a indicator to a bigger issue.

I guess that matches my observations above, "(I noticed, though, that Plasma on Wayland would automatically adapt to the hidpi display, apparently doing some scaling behind the scenes, while everything looked tiny with Plasma on X11.)"  But no idea whether and how that would have an impact here.  (When I asked him, Caolán assumed that it is more an issue of missing font hinting than of scaling.)

**Comment by rbrooklyn** [comment]
This looks to be a distro issue.

I've installed the KDE Neon distribution on this box. In both Wayland and X the mouse pointer looks identically sized, and Libreoffice's fonts look smooth.

I'm going to close this now, as I assume it's an Arch issue, or an issue with my specific installation at the very least. I never got to the bottom of it.

**Comment by YorozuyaDev** [comment]
I think is not a distro issue, having the same problem under swaywm (wayland)
