### ISSUE TITLE
How to print from a flatpak app?

### ISSUE THREAD

**Issue by SuffolkPunch** [flathub/org.libreoffice.LibreOffice#90]
I'm running flatpak (v 1.4.0-1~xenial) in LinuxMint 18.3 on my home PC.
I use CUPS to print from my home pc to a usb printer attached to my home server - both run LM 18.3.

I have installed the following flatpak apps:

>     net.scribus.Scribus/x86_64/stable
>     org.libreoffice.LibreOffice/x86_64/stable

My issue: Neither of these 2 apps sees my system printer. Instead, they just list a 'Generic Printer'. See pasted png image:
![printer-setup](https://user-images.githubusercontent.com/26813480/59591684-5d144c80-90e6-11e9-9fec-9fd267543cc3.png)
The drop-down list doesn't reveal any other printers.

My work-around - first export the file to pdf and then print from a non-flatpak pdf viewer!

So, does anyone know how you get a flatpak app to see printers that all the non-flatpak apps see?

**Comment by stbergmann** [comment]
(Works fine for me with the recent LO 6.2.4.2 flatpak on Fedora 30 GNOME/Wayland.  In e.g. Writer, "File - Printer Settings..." dialog lists the correct printer, not "Generic Printer".)

**Comment by SuffolkPunch** [comment]
@stbergmann: That's interesting - is your printer on the same PC or (as in my case) on the same LAN accessed via CUPS?

**Comment by SuffolkPunch** [comment]
Didn't mean to close this issue - hit the wrong icon, sorry. I am still seeking a fix.

**Comment by SuffolkPunch** [comment]
Please re-open this issue.

**Comment by stbergmann** [comment]
> @stbergmann: That's interesting - is your printer on the same PC or (as in my case) on the same LAN accessed via CUPS?

The latter, LAN via CUPS.

**Comment by eszlari** [comment]
Work here with my HP printer via USB:
Kubuntu 19.10
KDE Plasma 5.16.5
CUPS 2.2.12
flatpak 1.4.3

**Comment by Gwerlas** [comment]
Doesn't work with LAN printers
Fedora Silverblue 31
Cups 2.2.12
Flatpak 1.4.4

**Comment by Madko** [comment]
Same here on Fedora 32 Silverblue
Flatpak 1.6.3
Cups 2.3.1

I tried to give cups access to the LO flatpak thanks to flatseal, but no luck. Same with dbus acces. Is that a "green" tech to prevent waste of paper ? Pretty neat

**Comment by Erick555** [comment]
For me adding `--socket=cups` was enough to fix the issue.

Printer via LAN
Flatpak 1.8.1
Arch Linux

**Comment by scorpio810** [comment]
https://qelectrotech.org/forum/viewtopic.php?pid=14700#p14700

Maybe add --socket=cups

**Comment by geodro** [comment]
hey there, any updates on this?

**Comment by Erick555** [comment]
@geodro does solution from https://github.com/flathub/org.libreoffice.LibreOffice/issues/90#issuecomment-674214648 works for you?

**Comment by geodro** [comment]
> @geodro does solution from [#90 (comment)](https://github.com/flathub/org.libreoffice.LibreOffice/issues/90#issuecomment-674214648) works for you?

Sadly no. I have a network printer

**Comment by scorpio810** [comment]
--share=network - access the network?

**Comment by scorpio810** [comment]
https://musescore.org/en/node/270555

**Comment by geodro** [comment]
> --share=network - access the network?

not working also, I am using Fedora Silverblue 35 with the most recent updates.

![Screenshot from 2022-01-05 11-05-26](https://user-images.githubusercontent.com/289809/148191050-615bcc55-b6d5-4821-b705-e810b3832c4b.png)

**Comment by scorpio810** [comment]
Like?
`sudo snap connect musescore:cups-control`

**Comment by geodro** [comment]
> Like? `sudo snap connect musescore:cups-control`

I am using flatpak version of LibreOffice

**Comment by SuffolkPunch** [comment]
I had completely forgotten I started this issue 2½ years ago. Thanks for everyone's ideas. But, I no longer use flatpak versions of LibreOffice or Scribus, so lost interest. Happy if this issue is closed.

**Comment by fedelibre** [comment]
> not working also, I am using Fedora Silverblue 35 with the most recent updates.

@geodro I'm also using Silverblue and printing on LibreOffice has worked fine for a long time.

It seems you've not selected the right printer. In the LibreOffice dialog I see a *Generic Printer*, while in your printer settings the printer is called *HP Laserjet*. Can't you find it in the dropdown list of LibreOffice?

**Comment by geodro** [comment]
> @geodro I'm also using Silverblue and printing on LibreOffice has worked fine for a long time.
> 
> It seems you've not selected the right printer. In the LibreOffice dialog I see a _Generic Printer_, while in your printer settings the printer is called _HP Laserjet_. Can't you find it in the dropdown list of LibreOffice?

 The dialog in the screenshot is selected. The only options are Print to file and Generic Printer.

**Comment by fedelibre** [comment]
Weird... try undoing permission changes in Flatseal so you're sure you're using the same as me. For example, I don't have `socket=cups`enabled.

**Comment by geodro** [comment]
> Weird... try undoing permission changes in Flatseal so you're sure you're using the same as me. For example, I don't have `socket=cups`enabled.

I've undo the permissions and the behavior is the same. No printer seen.

**Comment by fedelibre** [comment]
Then @geodro I suggest you ask for help on https://ask.fedoraproject.org/

**Comment by Erick555** [comment]
It would be nice to check actual dbus address needed with `--log-system-bus` option. Allowing whole system bus access may be not acceptable solution.

**Comment by ahsodex** [comment]
Where is it supposed to log to? man flatpak-run doesn't say. I tried "flatpak run --log-system-bus org.libreoffice.LibreOffice" without the D-Bus permission, verified only the generic printer shows, then tried it again with D-Bus permission and verified my Epson printer shows and prints. I checked journalctl and only got this:
```
systemd[1633]: Started app-flatpak-org.libreoffice.LibreOffice-34909.scope.
systemd[1633]: app-flatpak-org.libreoffice.LibreOffice-34909.scope: Consumed 7.193s CPU time.
systemd[1633]: Started app-flatpak-org.libreoffice.LibreOffice-35066.scope.
systemd[1633]: app-flatpak-org.libreoffice.LibreOffice-35066.scope: Consumed 7.550s CPU time.
```

and this from the terminal:
```
(soffice:32): GLib-GObject-WARNING **: invalid cast from 'OOoAtkObjCompSel' to 'GtkWidgetAccessible'
(soffice:32): GLib-GObject-WARNING **: invalid cast from 'OOoAtkObjCompSel' to 'GtkWidgetAccessible'
(soffice:32): GLib-GObject-WARNING **: invalid cast from 'OOoAtkObjCompSel' to 'GtkWidgetAccessible'
(soffice:32): GLib-GObject-WARNING **: invalid cast from 'OOoAtkObjCompSel' to 'GtkWidgetAccessible'
(soffice:32): GLib-GObject-WARNING **: invalid cast from 'GtkBox' to 'GtkMenuShell'
(soffice:32): GLib-GObject-WARNING **: invalid cast from 'GtkBox' to 'GtkMenuShell'
```

**Comment by garrett** [comment]
> I realized the report comes from Fedora flaptak though not flathub so this is like apples & oranges comparison that may lead us nowhere.

Yeah, agreed. I've specifically chosen to use the Flathub version instead of the Fedora version of LibreOffice. It's nice to get the new releases ASAP. (Huge thanks to everyone who works on making LibreOffice on Flathub a reality! :partying_face:)

@ahsodex: If it's the Fedora Flatpak of LibreOffice, then that's definitely a bug that should be reported (at https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=libreoffice). You might also want to try the Flathub version instead, to see if printing works for you out of the box. (If it is the Flathub version, then you're at the right place.)

You can check the version like this:

```sh
flatpak list | grep libreoffice
```

And if it's from Flathub, results will look like this:

```
LibreOffice	org.libreoffice.LibreOffice	7.3.1.3	stable	flathub	system
```

**Comment by lightweight** [comment]
I'm running KDE Neon 20.04, with Thunderbird and Firefox installed via Flatpak. I was seeing the issue of no system printers visible in the print dialogue of either Flatpak app. I installed the Flatseal app (`sudo plasma-discover` and  then searched on Flatseal and installed it) so I could do as this report says - enable "Printing System" with `socket=cups`. Turns out it was already enabled. I disabled it, restarted FF and T-bird.. and voila, the system printers are now visible when printing. So it seems that for some apps in recent times, the opposite measure achieves the desired result. Hope that helps someone.

**Comment by ssokolow** [comment]
My best guess is that, with `socket=cups`, it uses direct CUPS access in a broken way while, without `socket=cups`, it's deferring to [`org.freedesktop.portal.Print`](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Print) and that doesn't have said bug.

(Perhaps it's using a mix of the two and doing something akin to getting a sandboxed file path from the File Chooser portal and then attempting to write a sibling file into the containing folder.)

**Comment by binary-adam** [comment]
Using flatseal to give access to DBus seemed to work for me - print dialog went from only having 'to pdf' to having my actual printer in it.

**Comment by bam80** [comment]
> This is on Fedora Silverblue 36 beta on GNOME 42 in Wayland with the automatic default driverless setting for my Brother printer. D-Bus is not enabled for either user or system.

@garrett could you retest on recent version as I and [other people](https://github.com/fedora-silverblue/issue-tracker/issues/642) still see the issue on the Silverblue?

**Comment by garrett** [comment]
I haven't had an issue on my personal desktop, but I don't see my printer on my work laptop. Both use Silverblue with the LibreOffice flatpak from Flathub and the same network printer.

**Comment by TheInfamousAlk** [comment]
> localhost:631

This is what solved it for me. I had my printer added via the "Printers" settings UI (Pop OS) but this added it a 2nd time via CUPS, and the CUPS copy of this printer worked after giving LibreOffice CUPS access via flatseal. Thank you!

**Comment by JaredTweed** [comment]
Can we re-open this issue until it is solved by default when libreoffice is downloaded as a flatpak? People really shouldn't have to do tinkering.
