### ISSUE TITLE
Can not enable OpenCL

### ISSUE THREAD

**Issue by akallabeth** [flathub/org.libreoffice.LibreOffice#97]
I´ve seen #82 and https://github.com/freedesktop/libreoffice-core/commit/db698a94ad52d1fbc387df66845907595615bb4f but from the commit message I assume it should be possible to enable OpenCL manually?

Anyway, tried this on multiple devices and after restarting libreoffice (as requested) the checkbox is unchecked again.

**Comment by stbergmann** [comment]
LO contains code that checks during startup whether OpenCL is actually supposed to work on the given machine and disables it again if not (see Desktop::CheckOpenCLCompute in desktop/source/app/opencl.cxx).  On two machines where I now tried this out, it consistently failed to enable OpenCL both for the latest Flathub LO 6.3.0.4 and for a local non-Flatpak master build.

In the context of this LO-Flatpak-specific issue, what would be of interest thus is a machine on which non-Flatpak LO allows to enable OpenCL while Flatpak LO does not.

**Comment by neildarlow** [comment]
I am running LibreOffice-7.0.0.3 as flatpak on a Toshiba Satellite P50-C-128. This machine has Optimus graphics (specifically NVidia GeForce 930M/Intel HD Graphics 5500) running in NVidia On-Demand mode.

I am able to select OpenCL in Options and, following restart of LibreOffice, the Help|About LibreOffice screen displays **Calc: CL**.

**Comment by stbergmann** [comment]
> I am able to select OpenCL in Options and, following restart of LibreOffice, the Help|About LibreOffice screen displays **Calc: CL**.

That statement is about the Flatpak LibreOffice 7.0.0.3, and not about another non-Flatpak LibreOffice on the same system?

**Comment by neildarlow** [comment]
Correct. I wanted to be sure that you were not approaching this problem as "Non-flatpak builds work with OpenCL but flatpak builds do not".

I have had varied experience with non-flatpak builds of LibreOffice and OpenCL support on this hardware. The last non-flatpak version of LibreOffice I used was 6.4.5 from the Ubuntu repository and 6.4.6.2 from the LibreOffice Packagers PPA. With both of these versions OpenGL could not be enabled.

So, for your specific requirements of above then I am unable to help but what can be said is that there are combinations of flatpak-built LibreOffice and OS and hardware that will permit OpenCL to be enabled. For additional information I am running Linux Mint 20 with the Cinnamon desktop (GTK3-based).

**Comment by stbergmann** [comment]
So close this as "there are machines where LibreOffice disables OpenCL because it is not known to work, and there are machines where LibreOffice (incl. Flatpak'ed versions) does allow to enable OpenCL".
