### ISSUE TITLE
Can't save to GVFS Google Drive

### ISSUE THREAD

**Issue by CharoSW** [flathub/org.libreoffice.LibreOffice#99]
Probably the same or similar issue to #23 I can't save to a document that was opened from the GVFS Google Drive folder. Ordinary distro provided Libreoffice saves documents opened from there fine.

**Comment by CharoSW** [comment]
I just retried this issue with the newly updated version that relies on the Freedesktop 20.08 and it still fails here

**Comment by ondrejholy** [comment]
I think that this can be closed as a duplicate of #23 as it doesn't contain anything new.

**Comment by CharoSW** [comment]
as your sort of solution from there works to fix the issue i'll close this one in favour of that
